In [ ]:
import json
import re
import time
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
from urllib.robotparser import RobotFileParser

import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
# Pasta para os dados brutos coletados
RAW = Path("dados_brutos")
RAW.mkdir(exist_ok=True)

# Pasta para a base tratada (integrada e limpa)
TRATADO = Path("dados_tratados")
TRATADO.mkdir(exist_ok=True)

# Cabeçalho de User-Agent:
HEADERS = {"User-Agent": "UFAM-CienciaDeDados-Trabalho1 (uso academico)"}

PAUSA = 2 # Pausa entre requisições em segundos

# Chave do Google Books API
GOOGLE_BOOKS_API_KEY = None
try:
    from google.colab import userdata
    GOOGLE_BOOKS_API_KEY = userdata.get("GOOGLE_BOOKS_API_KEY")
except Exception:
    import getpass
    GOOGLE_BOOKS_API_KEY = getpass.getpass(
        "Chave da Google Books API (Enter para pular): "
    ) or None

print("Ambiente pronto.")
print("pandas:", pd.__version__)
print("Chave da Google Books API configurada:", bool(GOOGLE_BOOKS_API_KEY))

Ambiente pronto.
pandas: 2.2.3
Chave da Google Books API configurada: True

In [ ]:
# Manter um registro que, para cada fonte, informe: de onde (URL exata), quando (data/hora da coleta), e como (método e parâmetros)
registro_proveniencia = []

def registrar_proveniencia(fonte, url, metodo, parametros=None, observacao=None):
    entrada = {
        "fonte": fonte,
        "url": url,
        "data_hora_coleta_utc": datetime.now(timezone.utc).isoformat(),
        "metodo": metodo,
        "parametros": parametros or {},
        "observacao": observacao or "",
    }
    registro_proveniencia.append(entrada)
    return entrada

def salvar_proveniencia(caminho=RAW / "proveniencia.json"):
    with open(caminho, "w", encoding="utf-8") as f:
        json.dump(registro_proveniencia, f, ensure_ascii=False, indent=2)
    print(f"Proveniência salva em: {caminho} ({len(registro_proveniencia)} entradas)")

In [ ]:
def raspar(url, user_agent="*"):
    # Verifica no robots.txt do site se a URL pode ser raspada.
    base = re.match(r"^(https?://[^/]+)", url).group(1)
    robots_url = urljoin(base, "/robots.txt")

    # Busca o robots.txt manualmente, com o mesmo User-Agent usado nas demais
    # requisições — a Wikimedia devolve 403 para o UA padrão do urllib, e
    # isso faz o RobotFileParser assumir "disallow all" por segurança.
    resp = requests.get(robots_url, headers=HEADERS, timeout=30)
    resp.raise_for_status()

    rp = RobotFileParser()
    rp.set_url(robots_url)
    rp.parse(resp.text.splitlines())  # em vez de rp.read()

    permitido = rp.can_fetch(user_agent, url)
    print(f"'robots.txt': {robots_url}")
    print(f"Permite acessar {url}? -> {permitido}")
    return permitido, robots_url

URL = "https://pt.wikipedia.org/wiki/Categoria:Livros_adaptados_para_o_cinema"
permitido, robots_url = raspar(URL)

registrar_proveniencia(
    fonte="Wikipedia (Pt) - Verificação do 'robots.txt'",
    url=robots_url,
    metodo="urllib.robotparser",
    observacao=f"can_fetch para {URL} = {permitido}",
)

assert permitido, "Robots.txt não permite o acesso."

'robots.txt': https://pt.wikipedia.org/robots.txt
Permite acessar https://pt.wikipedia.org/wiki/Categoria:Livros_adaptados_para_o_cinema? -> True

**Licença/termos de uso (Wikipédia):** o conteúdo textual da Wikipédia em português é distribuído
sob a licença **CC BY-SA 4.0** (Creative Commons Atribuição-CompartilhaIgual), o que permite uso,
cópia e redistribuição — inclusive para fins acadêmicos e comerciais — desde que se dê a devida
atribuição à fonte e que trabalhos derivados sejam compartilhados sob a mesma licença. Para este
projeto, extraímos apenas os títulos das obras e os links dos artigos (dados factuais, não o texto
integral dos artigos), o que está plenamente dentro dos termos de uso. A atribuição à Wikipédia está
registrada na coluna `url_artigo` da base e no registro de proveniência.

In [ ]:
# WebScraping

DIR_HTML_BRUTO = RAW / "wikipedia_html"
DIR_HTML_BRUTO.mkdir(exist_ok=True)


def baixar_pagina(url, indice_pagina):
    # Baixa uma página da categoria, salva o HTML bruto e retorna o BeautifulSoup.
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()

    caminho_html = DIR_HTML_BRUTO / f"categoria_pagina_{indice_pagina:02d}.html"
    caminho_html.write_text(resp.text, encoding="utf-8")

    registrar_proveniencia(
        fonte="Wikipedia (Pt) - Categoria: Livros_adaptados_para_o_cinema",
        url=resp.url,
        metodo="requests.get + BeautifulSoup",
        parametros={"pagina": indice_pagina, "status_http": resp.status_code},
        observacao=f"HTML bruto salvo em {caminho_html}",
    )

    return BeautifulSoup(resp.text, "html.parser")


def extrair_livros(soup):
    # Extrai (titulo, url_artigo) de cada item listado na página de categoria.
    livros = []
    container = soup.find("div", id="mw-pages")
    if container is None:
        return livros

    for link in container.select("div.mw-category-group ul li a"):
        titulo = link.get("title") or link.text.strip()
        href = link.get("href")
        if not href:
            continue
        url_artigo = urljoin("https://pt.wikipedia.org", href)
        livros.append({"titulo_wikipedia_sujo": titulo, "url_artigo": url_artigo})

    return livros


def proxima_pagina(soup):
    # Procura o link 'página seguinte' da categoria, se existir.
    container = soup.find("div", id="mw-pages")
    if container is None:
        return None
    for a in container.find_all("a"):
        if "página seguinte" in a.text.lower() or "next page" in a.text.lower():
            return urljoin("https://pt.wikipedia.org", a.get("href"))
    return None

In [ ]:
# Loop de coleta com paginação, sem sobrecarregar o servidor.

filmes = []
url_atual = URL
indice = 1

while url_atual:
    print(f"Coletando página {indice}: {url_atual}")
    soup = baixar_pagina(url_atual, indice)
    livros_pagina = extrair_livros(soup)
    print(f"  -> {len(livros_pagina)} títulos extraídos")
    filmes.extend(livros_pagina)

    url_atual = proxima_pagina(soup)
    indice += 1
    if url_atual:
        time.sleep(PAUSA)

print(f"\nTotal de filmes baseado em livros coletados: {len(filmes)}")

Coletando página 1: https://pt.wikipedia.org/wiki/Categoria:Livros_adaptados_para_o_cinema
  -> 200 títulos extraídos
Coletando página 2: https://pt.wikipedia.org/w/index.php?title=Categoria:Livros_adaptados_para_o_cinema&pagefrom=Josefine+Mutzenbacher#mw-pages
  -> 200 títulos extraídos
Coletando página 3: https://pt.wikipedia.org/w/index.php?title=Categoria:Livros_adaptados_para_o_cinema&pagefrom=Um+Antrop%C3%B3logo+em+Marte#mw-pages
  -> 24 títulos extraídos

Total de filmes baseado em livros coletados: 424

In [ ]:
def limpar_titulo(titulo):
    # Remove sufixos de desambiguação tipo '(livro)', '(romance)' etc.
    return re.sub(r"\s*\([^)]*\)\s*$", "", titulo).strip()

df_wikipedia_bruto = pd.DataFrame(filmes).drop_duplicates()
df_wikipedia_bruto["titulo_wikipedia"] = df_wikipedia_bruto["titulo_wikipedia_sujo"].apply(
    limpar_titulo
)

print(df_wikipedia_bruto.shape)
df_wikipedia_bruto.head()

(424, 3)

,titulo_wikipedia_sujo,url_artigo,titulo_wikipedia
0,Artur e os Minimeus (série),https://pt.wikipedia.org/wiki/Artur_e_os_Minim...,Artur e os Minimeus
1,1 Litre no Namida (livro),https://pt.wikipedia.org/wiki/1_Litre_no_Namid...,1 Litre no Namida
2,84 Charing Cross Road,https://pt.wikipedia.org/wiki/84_Charing_Cross...,84 Charing Cross Road
3,2010: Odyssey Two,https://pt.wikipedia.org/wiki/2010:_Odyssey_Two,2010: Odyssey Two
4,3096 Dias,https://pt.wikipedia.org/wiki/3096_Dias,3096 Dias

In [ ]:
# Dado bruto: exatamente como veio da extração, sem qualquer limpeza de conteúdo
caminho_csv_bruto = RAW / "wikipedia_livros_categoria.csv"
df_wikipedia_bruto.to_csv(caminho_csv_bruto, index=False, encoding="utf-8")

salvar_proveniencia()

print(f"Salvo: {caminho_csv_bruto}")

Proveniência salva em: dados_brutos/proveniencia.json (4 entradas)
Salvo: dados_brutos/wikipedia_livros_categoria.csv

**Licença/termos de uso (Google Books API):** o uso da API é regido pelos
[Termos de Serviço das APIs do Google](https://developers.google.com/terms) e pela política de uso
da Books API, que permite consultas para fins de pesquisa, desenvolvimento e uso acadêmico sem custo,
dentro dos limites de cota (requisições por dia). É proibido usar os dados para criar um serviço
concorrente ao Google Books ou redistribuir os dados brutos como produto próprio. Para este trabalho
acadêmico — que usa apenas metadados agregados (nota média, autor, editora, ano) e não redistribui a
API como serviço —, o uso está dentro do permitido.

In [ ]:
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
from urllib.robotparser import RobotFileParser

import pandas as pd
import requests
from bs4 import BeautifulSoup

# API

GOOGLEBOOKS_BRUTO = RAW / Path("google_books_json")
GOOGLEBOOKS_BRUTO.mkdir(exist_ok=True)

GOOGLE_BOOKS_ENDPOINT = "https://www.googleapis.com/books/v1/volumes"

def consultar_livros(titulo, indice, max_tentativas=3):
    # Consulta a Google Books API por um título e salva o JSON bruto da resposta.
    params = {"q": f"intitle:{titulo}"}
    if GOOGLE_BOOKS_API_KEY:
        params["key"] = GOOGLE_BOOKS_API_KEY

    for tentativa in range(1, max_tentativas + 1):
        resp = requests.get(
            GOOGLE_BOOKS_ENDPOINT, params=params, headers=HEADERS, timeout=30
        )

        if resp.status_code == 429 or resp.status_code == 503:
            # Cota excedida ou Serviço indisponível. Aguarda e tenta novamente.
            print(f"  {resp.status_code} (cota excedida ou serviço indisponível) para '{titulo}', tentativa {tentativa}. Aguardando...")
            time.sleep(PAUSA * 5) # Longer pause for server errors
            continue

        resp.raise_for_status()
        break
    else:
        raise RuntimeError(f"Falha ao consultar '{titulo}' após {max_tentativas} tentativas.")

    caminho_json = GOOGLEBOOKS_BRUTO / f"googlebooks_{indice:04d}.json"
    caminho_json.write_text(resp.text, encoding="utf-8")

    registrar_proveniencia(
        fonte="Google Books API",
        url=resp.url,
        metodo="requests.get (Google Books API v1/volumes)",
        parametros={"q": params["q"], "status_http": resp.status_code},
        observacao=f"JSON bruto salvo em {caminho_json}",
    )

    return resp.json()


def extrair_info(payload, titulo_wikipedia):
    # Extrai os campos de interesse do primeiro item retornado.
    itens = payload.get("items")
    if not itens:
        return {
            "titulo_wikipedia": titulo_wikipedia,
            "titulo_google_books": None,
            "autor": None,
            "ano_publicacao": None,
            "nota_media": None,
            "n_avaliacoes": None,
            "categorias": None,
            "idioma": None,
            "editora": None,
        }

    info = itens[0].get("volumeInfo", {})
    return {
        "titulo_wikipedia": titulo_wikipedia,
        "titulo_google_books": info.get("title"),
        "autor": ", ".join(info.get("authors", [])) or None,
        "ano_publicacao": info.get("publishedDate"),
        "nota_media": info.get("averageRating"),
        "n_avaliacoes": info.get("ratingsCount"),
        "categorias": ", ".join(info.get("categories", [])) or None,
        "idioma": info.get("language"),
        "editora": info.get("publisher"),
    }

In [ ]:
# Loop de coleta, reaproveitando os títulos já extraídos da Wikipédia

titulos_unicos = df_wikipedia_bruto["titulo_wikipedia"].dropna().unique()

resultados_livros = []

for i, titulo in enumerate(titulos_unicos, start=1):
    print(f"[{i}/{len(titulos_unicos)}] Consultando: {titulo}")
    payload = consultar_livros(titulo, i)
    resultados_livros.append(extrair_info(payload, titulo))
    time.sleep(PAUSA)

[1/424] Consultando: Artur e os Minimeus
[2/424] Consultando: 1 Litre no Namida
[3/424] Consultando: 84 Charing Cross Road
[4/424] Consultando: 2010: Odyssey Two
[5/424] Consultando: 3096 Dias
[6/424] Consultando: A Autobiografia de um Mentiroso: Volume VI
[7/424] Consultando: A Culpa É das Estrelas
[8/424] Consultando: À Espera de um Milagre
[9/424] Consultando: A Feiticeira
[10/424] Consultando: A Filosofia na Alcova
[11/424] Consultando: A Guerra dos Mundos
[12/424] Consultando: A Incendiária
[13/424] Consultando: A Little Princess
[14/424] Consultando: A Most Wanted Man
[15/424] Consultando: A Sangue Frio
[16/424] Consultando: A Vênus das Peles
[17/424] Consultando: About a Boy
[18/424] Consultando: Achados e Perdidos
[19/424] Consultando: The Adventures of Tom Sawyer
[20/424] Consultando: O Advogado do Diabo
[21/424] Consultando: Airport
[22/424] Consultando: Amanhecer
[23/424] Consultando: Amar, Verbo Intransitivo
[24/424] Consultando: Psicopata Americano
[25/424] Consultando: De amor y de sombra
[26/424] Consultando: L'amour dure trois ans
[27/424] Consultando: Ana e o Rei
[28/424] Consultando: Ana Terra
[29/424] Consultando: Antes que anochezca
[30/424] Consultando: Antes o Mundo Não Existia
[31/424] Consultando: Appointment with Death
[32/424] Consultando: O Aprendizado de Pequena Árvore
[33/424] Consultando: Arthur et la Cité interdite
[34/424] Consultando: Arthur et la Guerre des deux mondes
[35/424] Consultando: Arthur et la vengeance de Maltazard
[36/424] Consultando: Arthur et les Minimoys
[37/424] Consultando: The Killer Inside Me
[38/424] Consultando: Atlas Shrugged
[39/424] Consultando: Atonement
[40/424] Consultando: Austenlândia
[41/424] Consultando: Auto da Compadecida
[42/424] Consultando: Autobiografia de uma Pulga
[43/424] Consultando: As Aventuras de Huckleberry Finn
[44/424] Consultando: Basil of Baker Street
[45/424] Consultando: Beleza e Tristeza
[46/424] Consultando: Ben-Hur: A Tale of the Christ
[47/424] Consultando: Benjamim
[48/424] Consultando: Between a Rock and a Hard Place
[49/424] Consultando: The Bicentennial Man and Other Stories
[50/424] Consultando: Die Biene Maja
[51/424] Consultando: Born Free
[52/424] Consultando: The Boy in the Striped Pyjamas
[53/424] Consultando: Breve Romance de Sonho
[54/424] Consultando: Budapeste
[55/424] Consultando: Buddenbrooks: Verfall einer Familie
[56/424] Consultando: Bufo & Spallanzani
[57/424] Consultando: O Cabeleira
[58/424] Consultando: Call for the Dead
[59/424] Consultando: Call Me by Your Name
[60/424] Consultando: Camponeses
[61/424] Consultando: Canaã
[62/424] Consultando: Cannery Row
[63/424] Consultando: O Cão dos Baskervilles
[64/424] Consultando: A Carne
[65/424] Consultando: Uma Casa de Bonecas
[66/424] Consultando: La casa de los espíritus
[67/424] Consultando: Casino Royale
[68/424] Consultando: Catatau
[69/424] Consultando: Catching Fire
[70/424] Consultando: O Cavalinho Branco
[71/424] Consultando: Cazuza: Só as Mães São Felizes
[72/424] Consultando: Canção de Ninar
[73/424] Consultando: Charlotte's Web
[74/424] Consultando: O Cheiro do Ralo
[75/424] Consultando: Chitty-Chitty-Bang-Bang: The Magical Car
[76/424] Consultando: Christine
[77/424] Consultando: Cidade de Deus
[78/424] Consultando: Cidade dos Ossos
[79/424] Consultando: Cidades de Papel
[80/424] Consultando: Clifford the Big Red Dog
[81/424] Consultando: Clô Dias & Noites
[82/424] Consultando: Cloud Atlas
[83/424] Consultando: Cloudy with a Chance of Meatballs
[84/424] Consultando: Como Água para Chocolate
[85/424] Consultando: Como Se Tornar o Pior Aluno da Escola
[86/424] Consultando: O Conde de Monte Cristo
[87/424] Consultando: Contact
[88/424] Consultando: A Cor Púrpura
[89/424] Consultando: Falling Angel
[90/424] Consultando: Coraline
[91/424] Consultando: O Coronel e o Lobisomem
[92/424] Consultando: Crepúsculo
[93/424] Consultando: O Crime do Padre Amaro
[94/424] Consultando: Crônica da Casa Assassinada
[95/424] Consultando: A Cruz e o Punhal
[96/424] Consultando: The Curious Case of Benjamin Button
[97/424] Consultando: The Curse of Capistrano
[98/424] Consultando: Curtain
[99/424] Consultando: A Dama do Cachorrinho
[100/424] Consultando: A Dama do Lotação e Outros Contos e Crônicas
[101/424] Consultando: Dance on My Grave
[102/424] Consultando: Das geheime Leben der Bäume
[103/424] Consultando: Death on the Nile
[104/424] Consultando: Death Wish
[105/424] Consultando: Der Baader Meinhof Komplex
[106/424] Consultando: Desespero
[107/424] Consultando: Desgraça
[108/424] Consultando: O Diabo Veste Prada
[109/424] Consultando: Um Dia com Wilbur Robinson
[110/424] Consultando: O Diabo Apaixonado
[111/424] Consultando: Diamonds Are Forever
[112/424] Consultando: Diário de um pároco de aldeia
[113/424] Consultando: Diary of a Wimpy Kid: The Last Straw
[114/424] Consultando: Die Panne
[115/424] Consultando: Die Unendliche Geschichte
[116/424] Consultando: Do Androids Dream of Electric Sheep?
[117/424] Consultando: Dom Casmurro
[118/424] Consultando: Dona Flor e Seus Dois Maridos
[119/424] Consultando: Doutor Jivago
[120/424] Consultando: Dr. No
[121/424] Consultando: Drácula
[122/424] Consultando: Duna: Casa Harkonnen
[123/424] Consultando: East of Eden
[124/424] Consultando: Eclipse
[125/424] Consultando: Ecstasy: Three Tales of Chemical Romance
[126/424] Consultando: O Egípcio
[127/424] Consultando: Ele Está de Volta
[128/424] Consultando: Elite da Tropa
[129/424] Consultando: Elite da Tropa 2
[130/424] Consultando: Ella Encantada
[131/424] Consultando: Emma
[132/424] Consultando: The End of Eternity
[133/424] Consultando: Eneida
[134/424] Consultando: A Escrava Isaura
[135/424] Consultando: O Espião Que Saiu do Frio
[136/424] Consultando: Estação Carandiru
[137/424] Consultando: Estorvo
[138/424] Consultando: Estrela Solitária - Um Brasileiro Chamado Garrincha
[139/424] Consultando: Evil Under the Sun
[140/424] Consultando: Exit to Eden
[141/424] Consultando: Factotum
[142/424] Consultando: Fahrenheit 451
[143/424] Consultando: Fear and Loathing in Las Vegas
[144/424] Consultando: Fifty Shades of Grey
[145/424] Consultando: Flowers in the Attic
[146/424] Consultando: For Your Eyes Only
[147/424] Consultando: Forrest Gump
[148/424] Consultando: The Fountainhead
[149/424] Consultando: From Russia, with Love
[150/424] Consultando: Gabriela, Cravo e Canela
[151/424] Consultando: The Gadfly
[152/424] Consultando: O Gaúcho
[153/424] Consultando: Gerald's Game
[154/424] Consultando: Goldfinger
[155/424] Consultando: The Good Earth
[156/424] Consultando: The Graduate
[157/424] Consultando: O Grande Gatsby
[158/424] Consultando: O Grande Mentecapto
[159/424] Consultando: Gruppenbild mit Dame
[160/424] Consultando: O Guarani
[161/424] Consultando: Hamnet
[162/424] Consultando: Harry Potter and the Order of the Phoenix
[163/424] Consultando: Harry Potter and the Chamber of Secrets
[164/424] Consultando: Harry Potter e a Pedra Filosofal
[165/424] Consultando: Harry Potter and the Deathly Hallows
[166/424] Consultando: Harry Potter e o Cálice de Fogo
[167/424] Consultando: Harry Potter and the Half-Blood Prince
[168/424] Consultando: Harry Potter e o Prisioneiro de Azkaban
[169/424] Consultando: He's Just Not That Into You
[170/424] Consultando: Hodejegerne
[171/424] Consultando: Holes
[172/424] Consultando: O Homem Duplicado
[173/424] Consultando: O Homem Nu
[174/424] Consultando: A Hora da Estrela
[175/424] Consultando: The Host
[176/424] Consultando: Hotaru no Haka
[177/424] Consultando: The Hound of Death and Other Stories
[178/424] Consultando: The House of the Seven Gables
[179/424] Consultando: Howl's Moving Castle
[180/424] Consultando: The Human Stain
[181/424] Consultando: I Am Legend
[182/424] Consultando: I Am Number Four
[183/424] Consultando: I Know What You Did Last Summer
[184/424] Consultando: I Know Why the Caged Bird Sings
[185/424] Consultando: I, Claudius
[186/424] Consultando: I'm Thinking of Ending Things
[187/424] Consultando: Iaiá Garcia
[188/424] Consultando: L'île mystérieuse
[189/424] Consultando: Ilhas na Corrente
[190/424] Consultando: The Illustrated Man
[191/424] Consultando: Im Westen nichts Neues
[192/424] Consultando: In der Strafkolonie
[193/424] Consultando: Inocência
[194/424] Consultando: O Inverno do Nosso Descontentamento
[195/424] Consultando: Iracema
[196/424] Consultando: Ismael
[197/424] Consultando: It
[198/424] Consultando: A Jangada de Pedra
[199/424] Consultando: The Garden of Eden
[200/424] Consultando: O Jardim Secreto
[201/424] Consultando: Josefine Mutzenbacher
[202/424] Consultando: Jumanji
[203/424] Consultando: Justine
[204/424] Consultando: Kara no Kyoukai
[205/424] Consultando: The Kite Runner
[206/424] Consultando: Kleiner Mann – was nun?
[207/424] Consultando: L.A. Confidential
[208/424] Consultando: L'homme qui plantait des arbres
[209/424] Consultando: La invención de Morel
[210/424] Consultando: A Lagoa Azul
[211/424] Consultando: Last Summer
[212/424] Consultando: Laughter in the Dark
[213/424] Consultando: Lavoura Arcaica
[214/424] Consultando: Le Grand Meaulnes
[215/424] Consultando: Le Petit Prince
[216/424] Consultando: O Leitor
[217/424] Consultando: Les liaisons dangereuses
[218/424] Consultando: Life with Father
[219/424] Consultando: The Lightning Thief
[220/424] Consultando: Live and Let Die
[221/424] Consultando: Lolita
[222/424] Consultando: The Love of the Last Tycoon
[223/424] Consultando: The Lovely Bones
[224/424] Consultando: Lúcia McCartney
[225/424] Consultando: Lucíola
[226/424] Consultando: Lula, o Filho do Brasil
[227/424] Consultando: Luzia-Homem
[228/424] Consultando: Machenka
[229/424] Consultando: Macunaíma
[230/424] Consultando: O Mago
[231/424] Consultando: Main Street
[232/424] Consultando: Malu de Bicicleta
[233/424] Consultando: Män som hatar kvinnor
[234/424] Consultando: The Man with the Golden Gun
[235/424] Consultando: Manhã Transfigurada
[236/424] Consultando: Mansfield Park
[237/424] Consultando: Manuscrit trouvé à Saragosse
[238/424] Consultando: Mãos Vazias
[239/424] Consultando: Marley & Eu
[240/424] Consultando: A Marquesa d'O
[241/424] Consultando: O Matador
[242/424] Consultando: Maze Runner: Correr ou Morrer
[243/424] Consultando: Memórias do Cárcere
[244/424] Consultando: Memórias Póstumas de Brás Cubas
[245/424] Consultando: Memórias de uma Gueixa
[246/424] Consultando: As Meninas
[247/424] Consultando: O Menino Maluquinho
[248/424] Consultando: Message in a Bottle
[249/424] Consultando: Meu Pé de Laranja Lima
[250/424] Consultando: Minha Vida de Menina
[251/424] Consultando: Os Miseráveis
[252/424] Consultando: Mockingjay
[253/424] Consultando: O Monge
[254/424] Consultando: Moonraker
[255/424] Consultando: A Moreninha
[256/424] Consultando: Mortal Engines
[257/424] Consultando: Morte em Veneza
[258/424] Consultando: Mr. Popper's Penguins
[259/424] Consultando: Mudbound
[260/424] Consultando: Murder on the Orient Express
[261/424] Consultando: My Early Life
[262/424] Consultando: Mystic River
[263/424] Consultando: Naomi
[264/424] Consultando: Lua Nova
[265/424] Consultando: No Coração do Mar
[266/424] Consultando: No Country for Old Men
[267/424] Consultando: Noite
[268/424] Consultando: Northern Lights
[269/424] Consultando: O Alfaiate do Panamá
[270/424] Consultando: O Estranho Misterioso
[271/424] Consultando: O Exorcista
[272/424] Consultando: O Menino no Espelho
[273/424] Consultando: O Tigre e o Dragão
[274/424] Consultando: O Velho e o Mar
[275/424] Consultando: O Vendedor de Passados
[276/424] Consultando: Objeto Quase
[277/424] Consultando: A Obra ao Negro
[278/424] Consultando: Octopussy and The Living Daylights
[279/424] Consultando: Ratos e Homens
[280/424] Consultando: On Her Majesty's Secret Service
[281/424] Consultando: Ordeal by Innocence
[282/424] Consultando: Orgulho e Preconceito
[283/424] Consultando: El otoño del patriarca
[284/424] Consultando: Pantera no Porão
[285/424] Consultando: Os Pastores da Noite
[286/424] Consultando: O Pequeno Lord
[287/424] Consultando: Perdida
[288/424] Consultando: O Perfume
[289/424] Consultando: Pergunte ao Pó
[290/424] Consultando: The Perks of Being a Wallflower
[291/424] Consultando: Pet Sematary
[292/424] Consultando: Peter and Wendy
[293/424] Consultando: O Picapau Amarelo
[294/424] Consultando: Pimpinela Escarlate
[295/424] Consultando: La Planète des singes
[296/424] Consultando: Pollyanna
[297/424] Consultando: Bridge to Terabithia
[298/424] Consultando: As Pontes de Madison
[299/424] Consultando: Pop. 1280
[300/424] Consultando: Por Quem os Sinos Dobram
[301/424] Consultando: Postcards from the Edge
[302/424] Consultando: The Prince and the Pauper
[303/424] Consultando: Procura-se um Marido
[304/424] Consultando: Professor Unrat
[305/424] Consultando: O Que É Isso, Companheiro?
[306/424] Consultando: O Quinze
[307/424] Consultando: Riders of the Purple Sage
[308/424] Consultando: Rainbow 6
[309/424] Consultando: A Rainha Margot
[310/424] Consultando: Raise the Titanic!
[311/424] Consultando: O Pónei Vermelho
[312/424] Consultando: Rei, Dama, Valete
[313/424] Consultando: O Retrato de Dorian Gray
[314/424] Consultando: Retrato de uma Senhora
[315/424] Consultando: Return to Paradise
[316/424] Consultando: Ripley Subterrâneo
[317/424] Consultando: Rita Hayworth and Shawshank Redemption
[318/424] Consultando: Romance dos Três Reinos
[319/424] Consultando: Rouge Brésil
[320/424] Consultando: The Rum Diary
[321/424] Consultando: Rum Punch
[322/424] Consultando: The Runaway Jury
[323/424] Consultando: The Russia House
[324/424] Consultando: S. Bernardo
[325/424] Consultando: As Sandálias do Pescador
[326/424] Consultando: Sans Famille
[327/424] Consultando: Sargento Getúlio
[328/424] Consultando: Satíricon
[329/424] Consultando: Scarface
[330/424] Consultando: The Scarlet Letter
[331/424] Consultando: Schindler's Ark
[332/424] Consultando: The Sea of Monsters
[333/424] Consultando: Seabiscuit: An American Legend
[334/424] Consultando: Sem Destino
[335/424] Consultando: O Seminarista
[336/424] Consultando: Senhora
[337/424] Consultando: Sense and Sensibility
[338/424] Consultando: O Silêncio da Chuva
[339/424] Consultando: Sinhá-Moça
[340/424] Consultando: Sítio do Picapau Amarelo
[341/424] Consultando: Sob o Sol de Satã
[342/424] Consultando: O Som da Montanha
[343/424] Consultando: The Sound and the Fury
[344/424] Consultando: Spartacus
[345/424] Consultando: Stardust
[346/424] Consultando: Starter for Ten
[347/424] Consultando: Suite française
[348/424] Consultando: Sunrise on the Reaping
[349/424] Consultando: Die Weber
[350/424] Consultando: Tell No One
[351/424] Consultando: We Need to Talk About Kevin
[352/424] Consultando: And Then There Were None
[353/424] Consultando: Tenda dos Milagres
[354/424] Consultando: Tender Is the Night
[355/424] Consultando: Teresa Filósofa
[356/424] Consultando: Ziemia Obiecana
[357/424] Consultando: Tess dos d'Urbervilles
[358/424] Consultando: Thank You for Smoking
[359/424] Consultando: The Body Snatchers
[360/424] Consultando: The Case of the Howling Dog
[361/424] Consultando: The Constant Gardener
[362/424] Consultando: The Cruel Sea
[363/424] Consultando: The Death Cure
[364/424] Consultando: The Disaster Artist
[365/424] Consultando: The Executioners
[366/424] Consultando: The Friends of Eddie Coyle
[367/424] Consultando: The Handmaid's Tale
[368/424] Consultando: The Hate U Give
[369/424] Consultando: The Hundred and One Dalmatians
[370/424] Consultando: The Hunger Games
[371/424] Consultando: The Invention of Hugo Cabret
[372/424] Consultando: The Last of the Mohicans
[373/424] Consultando: The Little Drummer Girl
[374/424] Consultando: The Lost World
[375/424] Consultando: The Maltese Falcon
[376/424] Consultando: The Mothman Prophecies
[377/424] Consultando: The Prisoner of Zenda
[378/424] Consultando: The Red Badge of Courage
[379/424] Consultando: The Scorch Trials
[380/424] Consultando: The Shining
[381/424] Consultando: The Sun Also Rises
[382/424] Consultando: The Talented Mr. Ripley
[383/424] Consultando: The War of the Worlds
[384/424] Consultando: The Wettest County in the World
[385/424] Consultando: Thérèse Desqueyroux
[386/424] Consultando: Thérèse Raquin
[387/424] Consultando: Three Act Tragedy
[388/424] Consultando: Thunderball
[389/424] Consultando: Tieta do Agreste
[390/424] Consultando: Tinker Tailor Soldier Spy
[391/424] Consultando: Tirante o Branco
[392/424] Consultando: To Have an Have Not
[393/424] Consultando: Toda Nudez Será Castigada
[394/424] Consultando: Tomorrow, When the War Began
[395/424] Consultando: Tortilla Flat
[396/424] Consultando: Traumnovelle
[397/424] Consultando: Os Três Mosqueteiros
[398/424] Consultando: Tubarão
[399/424] Consultando: Turtles All the Way Down
[400/424] Consultando: A Última Tentação de Cristo
[401/424] Consultando: Um Antropólogo em Marte
[402/424] Consultando: Um Copo de Cólera
[403/424] Consultando: Um de Nós
[404/424] Consultando: Um Dia
[405/424] Consultando: Um Quarto de Légua em Quadro
[406/424] Consultando: Uma Casa no Fim do Mundo
[407/424] Consultando: Up in the Air
[408/424] Consultando: A Vegetariana
[409/424] Consultando: Verity
[410/424] Consultando: Veronika Decide Morrer
[411/424] Consultando: Vidas Secas
[412/424] Consultando: O Videota
[413/424] Consultando: As Vinhas da Ira
[414/424] Consultando: VIPs: Histórias Reais de um Mentiroso
[415/424] Consultando: Water for Elephants
[416/424] Consultando: Where the Red Fern Grows
[417/424] Consultando: Wired
[418/424] Consultando: A Wizard of Earthsea
[419/424] Consultando: The World According to Garp
[420/424] Consultando: Wuthering Heights
[421/424] Consultando: You Only Live Twice
[422/424] Consultando: Yukiguni
[423/424] Consultando: Z for Zachariah
[424/424] Consultando: Zorba, o Grego

In [ ]:
df_google_books_bruto = pd.DataFrame(resultados_livros)
df_google_books_bruto.head(50)

,titulo_wikipedia,titulo_google_books,autor,ano_publicacao,nota_media,n_avaliacoes,categorias,idioma,editora
0,Artur e os Minimeus,Arthur and the Minimoys,Luc Besson,2006-04-25,4.0,1.0,Juvenile Fiction,en,Harper Collins
1,1 Litre no Namida,1 Litre of Tears,Kito Aya,2024-09-11,NaN,NaN,Biography & Autobiography,vi,None
2,84 Charing Cross Road,"84, Charing Cross Road",Helene Hanff,2027-02-02,NaN,NaN,Literary Collections,en,Penguin Classics
3,2010: Odyssey Two,2010: Odyssey Two,Arthur C. Clarke,1984-01-12,4.0,18.0,Fiction,en,Del Rey
4,3096 Dias,"3,096 Days","Natascha Kampusch, Heike Gronemeier, Corinna M...",2010-09-16,NaN,NaN,Biography & Autobiography,en,Penguin UK
5,A Autobiografia de um Mentiroso: Volume VI,Vi-a Mais Sacra,Melkyzedek Siqueira César,2024-05-05,NaN,NaN,Biography & Autobiography,pt-BR,Clube de Autores
6,A Culpa É das Estrelas,A Culpa Não É Das Estrelas,Daniel Carlos,2022-06-04,NaN,NaN,Education,pt-BR,Clube de Autores
7,À Espera de um Milagre,À Espera Da Extraordinária Cura,Marinalva Irenice Conceição; Guilherme Do Espí...,2025-05-05,NaN,NaN,Humor,pt-BR,Clube de Autores
8,A Feiticeira,"Winnie, a Feiticeira","Korky Paul, Valerie Thomas",1998,NaN,NaN,Cats,pt-BR,Martins Martins Fontes
9,A Filosofia na Alcova,"Filosofia na Alcôva, A",marquis de Sade,2000,5.0,1.0,Fiction,pt-BR,Editora Iluminuras Ltda
10,A Guerra dos Mundos,Workbook/Lab Manual Part A to Accompany DOS Mu...,"Tracy D. Terrell, Magdalena Andrade, Jeanne Eg...",2001-10,NaN,NaN,Foreign Language Study,en,"McGraw-Hill Humanities, Social Sciences & Worl..."
11,A Incendiária,A incendiária,Stephen King,2018-04-06,NaN,NaN,Fiction,pt-BR,Suma
12,A Little Princess,A Little Princess,Frances Hodgson Burnett,2020-12-08,NaN,NaN,Juvenile Fiction,en,Graphic Arts Books
13,A Most Wanted Man,A Most Wanted Man,John le Carre,2014-07,NaN,NaN,Fiction,en,Simon and Schuster
14,A Sangue Frio,A sangue frio,Truman Capote,2003-09-16,NaN,NaN,True Crime,pt-BR,Editora Companhia das Letras
15,A Vênus das Peles,A Vênus das peles [Bolso],Leopold Von Sacher-Masoch,2008-01-03,NaN,NaN,Fiction,pt-BR,None
16,About a Boy,About a Boy,Nick Hornby,1999-05-01,4.0,6.0,Fiction,en,Penguin
17,Achados e Perdidos,Achados e perdidos,"Concha Celestino, Cris Gonzalez, Deborah Dorne...",2014-09-11,NaN,NaN,Fiction,pt-BR,e-galáxia
18,The Adventures of Tom Sawyer,The Adventures of Tom Sawyer,Mark Twain,1999,4.0,6.0,Juvenile Fiction,en,Scholastic Inc.
19,O Advogado do Diabo,O advogado do diabo,Morris West,1959,NaN,NaN,None,pt-BR,None
20,Airport,Local Climatological Data,None,2007,NaN,NaN,Detroit (Mich.),en,None
21,Amanhecer,Jaguars of the Dawn,Emily Pierini,2020-01-10,NaN,NaN,Religion,en,Berghahn Books
22,"Amar, Verbo Intransitivo","Amar, verbo intransitivo (romance)",Mário de Andrade,1960,NaN,NaN,Brazilian literature,pt-BR,None
23,Psicopata Americano,O psicopata Americano,Bret Easton Ellis,1992,NaN,NaN,None,pt-BR,None
24,De amor y de sombra,De amor y de sombra,Isabel Allende,2009,NaN,NaN,None,es,None
25,L'amour dure trois ans,Love Lasts Three Years,Kerry M. Harwin,2005,NaN,NaN,City and town life in literature,en,None
26,Ana e o Rei,Ana a manda,Ruy Duarte de Carvalho,1989,NaN,NaN,Angola,pt-BR,None
27,Ana Terra,"Ana Theodora, mulher-do-chifre-furado",Mariana de Oliveira,1992,NaN,NaN,Women,pt-BR,None
28,Antes que anochezca,Antes Que Anochezca,None,2001-01-01,NaN,NaN,Cuba,en,New Line Cinema Corporation
29,Antes o Mundo Não Existia,Antes o mundo não existia,"Umúsin Panlõn Kumu, Tolamãn Kenhíri",1995,NaN,NaN,Desana mythology,pt-BR,None
30,Appointment with Death,Appointment with Death,Agatha Christie,2011-09-27,NaN,NaN,Fiction,en,Harper Collins
31,O Aprendizado de Pequena Árvore,O aprendizado de Pequena Árvore,Forrest Carter,1994,NaN,NaN,None,pt-BR,None
32,Arthur et la Cité interdite,Arthur et la cité interdite,"Luc Besson, Céline Garcia",2005,NaN,NaN,None,fr,None
33,Arthur et la Guerre des deux mondes,Arthur 3 - La guerre des deux mondes,"Besson,",2010-10-06,NaN,NaN,None,fr,Intervista
34,Arthur et la vengeance de Maltazard,Arthur et la vengeance de Maltazard,"Luc Besson, Stéphane Martinez, Robert Cepo",2009-11-12,NaN,NaN,None,fr,None
35,Arthur et les Minimoys,Arthur et les minimoys T02,Jean-Christophe Derrien,2019-10-30,NaN,NaN,Comics & Graphic Novels,fr,Soleil
36,The Killer Inside Me,The Killer Inside Me,Jim Thompson,2011-11-01,4.0,17.0,Fiction,en,Hachette+ORM
37,Atlas Shrugged,Atlas Shrugged,Ayn Rand,2005-04-21,4.0,6.0,Fiction,en,Penguin
38,Atonement,The Atonement,William Lane Craig,2018-06-21,NaN,NaN,Religion,en,Cambridge University Press
39,Austenlândia,Austenlândia,Shannon Hale,2014-07-31,NaN,NaN,Fiction,pt-BR,Editora Record
40,Auto da Compadecida,Auto Da Compadecida,A. Suassuna,1967,NaN,NaN,None,en,None
41,Autobiografia de uma Pulga,Autobiografia de uma pulga,Anônimo,2015-08-31,NaN,NaN,Fiction,pt-BR,hedra
42,As Aventuras de Huckleberry Finn,As aventuras de Huckleberry Finn,Mark Twain,2011-08-16,NaN,NaN,Fiction,pt-BR,Editora Best Seller
43,Basil of Baker Street,Basil of Baker Street,"Eve Titus, Paul Galdone",2016-05-17,NaN,NaN,Juvenile Fiction,en,Simon and Schuster
44,Beleza e Tristeza,Beleza e tristeza,Yasunari Kawabata,2008,NaN,NaN,None,pt-BR,None
45,Ben-Hur: A Tale of the Christ,Ben-Hur: A tale of the Christ,Lew Wallace,2022-05-28,NaN,NaN,Fiction,en,DigiCat
46,Benjamim,Circo-Teatro: Benjamim de Oliveira e a teatral...,Ermínia Silva,2022-09-01,NaN,NaN,Education,pt-BR,Digitaliza Conteudo
47,Between a Rock and a Hard Place,Between a Rock and a Hard Place,Aron Ralston,2004-09-15,3.5,13.0,Biography & Autobiography,en,Simon and Schuster
48,The Bicentennial Man and Other Stories,The Bicentennial Man and Other Stories,Isaac Asimov,1981-07-12,5.0,1.0,None,en,Fawcett
49,Die Biene Maja,Die Biene Maja Und Ihre Abenteuer,"Waldemar Bonsels, Franz Schneider, Martha Boyd",2026-02-14,NaN,NaN,Language Study,en,Tradd Street Press

In [ ]:
# Dado bruto: exatamente como veio da API, sem qualquer limpeza de conteúdo
caminho_csv_gb = RAW / "google_books_resultados.csv"
df_google_books_bruto.to_csv(caminho_csv_gb, index=False, encoding="utf-8")

salvar_proveniencia()  # reescreve o log completo (Wikipedia + Google Books)

print(f"Salvo: {caminho_csv_gb}")

Proveniência salva em: dados_brutos/proveniencia.json (428 entradas)
Salvo: dados_brutos/google_books_resultados.csv

In [ ]:
# Contando o número de valores nulos (NaN) em cada coluna
missing_values = df_google_books_bruto.isnull().sum()
print("Contagem de valores ausentes por coluna:")
print(missing_values[missing_values > 0])

Contagem de valores ausentes por coluna:
titulo_google_books      1
autor                   20
ano_publicacao          11
nota_media             341
n_avaliacoes           341
categorias             125
idioma                   1
editora                182
dtype: int64

In [ ]:
# Calculando a porcentagem de valores ausentes por coluna
missing_percentage = (df_google_books_bruto.isnull().sum() / len(df_google_books_bruto)) * 100
print("\nPorcentagem de valores ausentes por coluna:")
print(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

Porcentagem de valores ausentes por coluna:
nota_media             80.424528
n_avaliacoes           80.424528
editora                42.924528
categorias             29.481132
autor                   4.716981
ano_publicacao          2.594340
titulo_google_books     0.235849
idioma                  0.235849
dtype: float64

## Terceira fonte: TMDB API (dados dos filmes)

Até aqui temos:
- **Wikipédia (scraping):** lista de livros adaptados para o cinema (`titulo_wikipedia`).
- **Google Books API:** avaliação dos leitores sobre o **livro** (`nota_media`, `n_avaliacoes`, etc.).

Falta o lado do **filme**: bilheteria, orçamento, nota do público, popularidade, data de
lançamento. Isso vem da **TMDB (The Movie Database) API** — uma API pública, gratuita para
uso não comercial mediante cadastro, amplamente usada em projetos acadêmicos.

**Como obter a chave (token):**
1. Crie uma conta em https://www.themoviedb.org/ (gratuita).
2. Vá em *Configurações → API* e solicite uma chave (aprovação é automática para uso pessoal/educacional).
3. Você recebe duas credenciais: a **API Key (v3)** e o **Access Token (v4, Bearer)**. Usaremos o
   token v4 no cabeçalho `Authorization`, no mesmo padrão de autenticação "token no header" visto para
   a API do GitHub (Módulo 3 da disciplina).

**Licença/termos de uso:** a TMDB exige que o uso da API cite a atribuição *"This product uses the
TMDB API but is not endorsed or certified by TMDB"* em qualquer produto que a utilize, e proíbe uso
que viole seus Termos de Serviço (ex.: revender os dados brutos como um produto concorrente). Para um
trabalho acadêmico, o uso é permitido.

In [ ]:
# Configuração da TMDB API
TMDB_TOKEN = None
try:
    from google.colab import userdata
    TMDB_TOKEN = userdata.get("TMDB_TOKEN")
except Exception:
    import getpass
    TMDB_TOKEN = getpass.getpass(
        "Token (Bearer v4) da TMDB API (Enter para pular): "
    ) or None

TMDB_ENDPOINT_SEARCH = "https://api.themoviedb.org/3/search/movie"
TMDB_ENDPOINT_DETAILS = "https://api.themoviedb.org/3/movie/{id}"

TMDB_HEADERS = dict(HEADERS)  # reaproveita o User-Agent definido antes
if TMDB_TOKEN:
    TMDB_HEADERS["Authorization"] = f"Bearer {TMDB_TOKEN}"

TMDB_BRUTO = RAW / "tmdb_json"
TMDB_BRUTO.mkdir(exist_ok=True)

print("Chave da TMDB API configurada:", bool(TMDB_TOKEN))

Chave da TMDB API configurada: True

In [ ]:
def buscar_filme_tmdb(titulo, indice, max_tentativas=3):
    # Busca um filme pelo título na TMDB e salva o JSON bruto da resposta de busca.
    params = {"query": titulo, "language": "pt-BR", "include_adult": "false"}

    for tentativa in range(1, max_tentativas + 1):
        resp = requests.get(
            TMDB_ENDPOINT_SEARCH, params=params, headers=TMDB_HEADERS, timeout=30
        )

        if resp.status_code == 429:
            # Cota/limite de requisições excedido
            espera = int(resp.headers.get("Retry-After", PAUSA * 5))
            print(f"  429 (limite excedido) para '{titulo}', tentativa {tentativa}. Aguardando {espera}s...")
            time.sleep(espera)
            continue

        resp.raise_for_status()
        break
    else:
        raise RuntimeError(f"Falha ao buscar '{titulo}' na TMDB após {max_tentativas} tentativas.")

    caminho_json = TMDB_BRUTO / f"tmdb_busca_{indice:04d}.json"
    caminho_json.write_text(resp.text, encoding="utf-8")

    registrar_proveniencia(
        fonte="TMDB API - busca por filme",
        url=resp.url,
        metodo="requests.get (TMDB /search/movie)",
        parametros={"query": titulo, "status_http": resp.status_code},
        observacao=f"JSON bruto salvo em {caminho_json}",
    )

    return resp.json()


def detalhar_filme_tmdb(tmdb_id, indice, max_tentativas=3):
    # Consulta os detalhes de um filme (orçamento, receita, duração, gêneros)
    # e salva o JSON bruto da resposta.
    url = TMDB_ENDPOINT_DETAILS.format(id=tmdb_id)
    params = {"language": "pt-BR"}

    for tentativa in range(1, max_tentativas + 1):
        resp = requests.get(url, params=params, headers=TMDB_HEADERS, timeout=30)

        if resp.status_code == 429:
            espera = int(resp.headers.get("Retry-After", PAUSA * 5))
            print(f"  429 (limite excedido) para id={tmdb_id}, tentativa {tentativa}. Aguardando {espera}s...")
            time.sleep(espera)
            continue

        resp.raise_for_status()
        break
    else:
        raise RuntimeError(f"Falha ao detalhar filme id={tmdb_id} após {max_tentativas} tentativas.")

    caminho_json = TMDB_BRUTO / f"tmdb_detalhes_{indice:04d}.json"
    caminho_json.write_text(resp.text, encoding="utf-8")

    registrar_proveniencia(
        fonte="TMDB API - detalhes do filme",
        url=resp.url,
        metodo="requests.get (TMDB /movie/{id})",
        parametros={"tmdb_id": tmdb_id, "status_http": resp.status_code},
        observacao=f"JSON bruto salvo em {caminho_json}",
    )

    return resp.json()


def extrair_info_tmdb(titulo_wikipedia, busca_payload, detalhes_payload):
    # Extrai os campos de interesse combinando a busca (relevância/ordenação)
    # com os detalhes (orçamento, receita, duração, gêneros).
    if detalhes_payload is None:
        return {
            "titulo_wikipedia": titulo_wikipedia,
            "tmdb_id": None,
            "titulo_tmdb": None,
            "data_lancamento": None,
            "idioma_original": None,
            "generos": None,
            "duracao_min": None,
            "orcamento": None,
            "receita": None,
            "popularidade": None,
            "media_votos": None,
            "contagem_votos": None,
        }

    generos = ", ".join(g["name"] for g in detalhes_payload.get("genres", [])) or None

    return {
        "titulo_wikipedia": titulo_wikipedia,
        "tmdb_id": detalhes_payload.get("id"),
        "titulo_tmdb": detalhes_payload.get("title"),
        "data_lancamento": detalhes_payload.get("release_date") or None,
        "idioma_original": detalhes_payload.get("original_language"),
        "generos": generos,
        "duracao_min": detalhes_payload.get("runtime"),
        "orcamento": detalhes_payload.get("budget"),
        "receita": detalhes_payload.get("revenue"),
        "popularidade": detalhes_payload.get("popularity"),
        "media_votos": detalhes_payload.get("vote_average"),
        "contagem_votos": detalhes_payload.get("vote_count"),
    }

In [ ]:
# Loop de coleta, reaproveitando os mesmos títulos já usados no Google Books
resultados_tmdb = []

for i, titulo in enumerate(titulos_unicos, start=1):
    print(f"[{i}/{len(titulos_unicos)}] Buscando na TMDB: {titulo}")

    busca = buscar_filme_tmdb(titulo, i)
    candidatos = busca.get("results") or []

    if not candidatos:
        print("  -> nenhum resultado encontrado")
        resultados_tmdb.append(extrair_info_tmdb(titulo, busca, None))
        time.sleep(PAUSA)
        continue

    # A TMDB já ordena os resultados por relevância/popularidade; usamos o primeiro.
    melhor_candidato = candidatos[0]
    time.sleep(PAUSA)

    detalhes = detalhar_filme_tmdb(melhor_candidato["id"], i)
    resultados_tmdb.append(extrair_info_tmdb(titulo, busca, detalhes))
    time.sleep(PAUSA)

print(f"\nTotal de consultas TMDB realizadas: {len(resultados_tmdb)}")

[1/424] Buscando na TMDB: Artur e os Minimeus
[2/424] Buscando na TMDB: 1 Litre no Namida
[3/424] Buscando na TMDB: 84 Charing Cross Road
[4/424] Buscando na TMDB: 2010: Odyssey Two
[5/424] Buscando na TMDB: 3096 Dias
[6/424] Buscando na TMDB: A Autobiografia de um Mentiroso: Volume VI
  -> nenhum resultado encontrado
[7/424] Buscando na TMDB: A Culpa É das Estrelas
[8/424] Buscando na TMDB: À Espera de um Milagre
[9/424] Buscando na TMDB: A Feiticeira
[10/424] Buscando na TMDB: A Filosofia na Alcova
[11/424] Buscando na TMDB: A Guerra dos Mundos
[12/424] Buscando na TMDB: A Incendiária
[13/424] Buscando na TMDB: A Little Princess
[14/424] Buscando na TMDB: A Most Wanted Man
[15/424] Buscando na TMDB: A Sangue Frio
[16/424] Buscando na TMDB: A Vênus das Peles
  -> nenhum resultado encontrado
[17/424] Buscando na TMDB: About a Boy
[18/424] Buscando na TMDB: Achados e Perdidos
[19/424] Buscando na TMDB: The Adventures of Tom Sawyer
[20/424] Buscando na TMDB: O Advogado do Diabo
[21/424] Buscando na TMDB: Airport
[22/424] Buscando na TMDB: Amanhecer
[23/424] Buscando na TMDB: Amar, Verbo Intransitivo
  -> nenhum resultado encontrado
[24/424] Buscando na TMDB: Psicopata Americano
[25/424] Buscando na TMDB: De amor y de sombra
[26/424] Buscando na TMDB: L'amour dure trois ans
[27/424] Buscando na TMDB: Ana e o Rei
[28/424] Buscando na TMDB: Ana Terra
[29/424] Buscando na TMDB: Antes que anochezca
[30/424] Buscando na TMDB: Antes o Mundo Não Existia
[31/424] Buscando na TMDB: Appointment with Death
[32/424] Buscando na TMDB: O Aprendizado de Pequena Árvore
  -> nenhum resultado encontrado
[33/424] Buscando na TMDB: Arthur et la Cité interdite
  -> nenhum resultado encontrado
[34/424] Buscando na TMDB: Arthur et la Guerre des deux mondes
[35/424] Buscando na TMDB: Arthur et la vengeance de Maltazard
[36/424] Buscando na TMDB: Arthur et les Minimoys
[37/424] Buscando na TMDB: The Killer Inside Me
[38/424] Buscando na TMDB: Atlas Shrugged
[39/424] Buscando na TMDB: Atonement
[40/424] Buscando na TMDB: Austenlândia
  -> nenhum resultado encontrado
[41/424] Buscando na TMDB: Auto da Compadecida
[42/424] Buscando na TMDB: Autobiografia de uma Pulga
  -> nenhum resultado encontrado
[43/424] Buscando na TMDB: As Aventuras de Huckleberry Finn
[44/424] Buscando na TMDB: Basil of Baker Street
  -> nenhum resultado encontrado
[45/424] Buscando na TMDB: Beleza e Tristeza
  -> nenhum resultado encontrado
[46/424] Buscando na TMDB: Ben-Hur: A Tale of the Christ
[47/424] Buscando na TMDB: Benjamim
[48/424] Buscando na TMDB: Between a Rock and a Hard Place
[49/424] Buscando na TMDB: The Bicentennial Man and Other Stories
  -> nenhum resultado encontrado
[50/424] Buscando na TMDB: Die Biene Maja
[51/424] Buscando na TMDB: Born Free
[52/424] Buscando na TMDB: The Boy in the Striped Pyjamas
[53/424] Buscando na TMDB: Breve Romance de Sonho
  -> nenhum resultado encontrado
[54/424] Buscando na TMDB: Budapeste
[55/424] Buscando na TMDB: Buddenbrooks: Verfall einer Familie
  -> nenhum resultado encontrado
[56/424] Buscando na TMDB: Bufo & Spallanzani
[57/424] Buscando na TMDB: O Cabeleira
[58/424] Buscando na TMDB: Call for the Dead
  -> nenhum resultado encontrado
[59/424] Buscando na TMDB: Call Me by Your Name
[60/424] Buscando na TMDB: Camponeses
[61/424] Buscando na TMDB: Canaã
[62/424] Buscando na TMDB: Cannery Row
[63/424] Buscando na TMDB: O Cão dos Baskervilles
[64/424] Buscando na TMDB: A Carne
[65/424] Buscando na TMDB: Uma Casa de Bonecas
  -> nenhum resultado encontrado
[66/424] Buscando na TMDB: La casa de los espíritus
[67/424] Buscando na TMDB: Casino Royale
[68/424] Buscando na TMDB: Catatau
  -> nenhum resultado encontrado
[69/424] Buscando na TMDB: Catching Fire
[70/424] Buscando na TMDB: O Cavalinho Branco
[71/424] Buscando na TMDB: Cazuza: Só as Mães São Felizes
  -> nenhum resultado encontrado
[72/424] Buscando na TMDB: Canção de Ninar
[73/424] Buscando na TMDB: Charlotte's Web
[74/424] Buscando na TMDB: O Cheiro do Ralo
[75/424] Buscando na TMDB: Chitty-Chitty-Bang-Bang: The Magical Car
  -> nenhum resultado encontrado
[76/424] Buscando na TMDB: Christine
[77/424] Buscando na TMDB: Cidade de Deus
[78/424] Buscando na TMDB: Cidade dos Ossos
[79/424] Buscando na TMDB: Cidades de Papel
[80/424] Buscando na TMDB: Clifford the Big Red Dog
[81/424] Buscando na TMDB: Clô Dias & Noites
  -> nenhum resultado encontrado
[82/424] Buscando na TMDB: Cloud Atlas
[83/424] Buscando na TMDB: Cloudy with a Chance of Meatballs
[84/424] Buscando na TMDB: Como Água para Chocolate
[85/424] Buscando na TMDB: Como Se Tornar o Pior Aluno da Escola
[86/424] Buscando na TMDB: O Conde de Monte Cristo
[87/424] Buscando na TMDB: Contact
[88/424] Buscando na TMDB: A Cor Púrpura
[89/424] Buscando na TMDB: Falling Angel
[90/424] Buscando na TMDB: Coraline
[91/424] Buscando na TMDB: O Coronel e o Lobisomem
[92/424] Buscando na TMDB: Crepúsculo
[93/424] Buscando na TMDB: O Crime do Padre Amaro
[94/424] Buscando na TMDB: Crônica da Casa Assassinada
  -> nenhum resultado encontrado
[95/424] Buscando na TMDB: A Cruz e o Punhal
[96/424] Buscando na TMDB: The Curious Case of Benjamin Button
[97/424] Buscando na TMDB: The Curse of Capistrano
  -> nenhum resultado encontrado
[98/424] Buscando na TMDB: Curtain
[99/424] Buscando na TMDB: A Dama do Cachorrinho
[100/424] Buscando na TMDB: A Dama do Lotação e Outros Contos e Crônicas
  -> nenhum resultado encontrado
[101/424] Buscando na TMDB: Dance on My Grave
[102/424] Buscando na TMDB: Das geheime Leben der Bäume
[103/424] Buscando na TMDB: Death on the Nile
[104/424] Buscando na TMDB: Death Wish
[105/424] Buscando na TMDB: Der Baader Meinhof Komplex
[106/424] Buscando na TMDB: Desespero
[107/424] Buscando na TMDB: Desgraça
[108/424] Buscando na TMDB: O Diabo Veste Prada
[109/424] Buscando na TMDB: Um Dia com Wilbur Robinson
  -> nenhum resultado encontrado
[110/424] Buscando na TMDB: O Diabo Apaixonado
  -> nenhum resultado encontrado
[111/424] Buscando na TMDB: Diamonds Are Forever
[112/424] Buscando na TMDB: Diário de um pároco de aldeia
[113/424] Buscando na TMDB: Diary of a Wimpy Kid: The Last Straw
[114/424] Buscando na TMDB: Die Panne
[115/424] Buscando na TMDB: Die Unendliche Geschichte
[116/424] Buscando na TMDB: Do Androids Dream of Electric Sheep?
  -> nenhum resultado encontrado
[117/424] Buscando na TMDB: Dom Casmurro
[118/424] Buscando na TMDB: Dona Flor e Seus Dois Maridos
[119/424] Buscando na TMDB: Doutor Jivago
[120/424] Buscando na TMDB: Dr. No
[121/424] Buscando na TMDB: Drácula
[122/424] Buscando na TMDB: Duna: Casa Harkonnen
  -> nenhum resultado encontrado
[123/424] Buscando na TMDB: East of Eden
[124/424] Buscando na TMDB: Eclipse
[125/424] Buscando na TMDB: Ecstasy: Three Tales of Chemical Romance
  -> nenhum resultado encontrado
[126/424] Buscando na TMDB: O Egípcio
[127/424] Buscando na TMDB: Ele Está de Volta
[128/424] Buscando na TMDB: Elite da Tropa
  -> nenhum resultado encontrado
[129/424] Buscando na TMDB: Elite da Tropa 2
  -> nenhum resultado encontrado
[130/424] Buscando na TMDB: Ella Encantada
[131/424] Buscando na TMDB: Emma
[132/424] Buscando na TMDB: The End of Eternity
[133/424] Buscando na TMDB: Eneida
[134/424] Buscando na TMDB: A Escrava Isaura
[135/424] Buscando na TMDB: O Espião Que Saiu do Frio
[136/424] Buscando na TMDB: Estação Carandiru
  -> nenhum resultado encontrado
[137/424] Buscando na TMDB: Estorvo
[138/424] Buscando na TMDB: Estrela Solitária - Um Brasileiro Chamado Garrincha
  -> nenhum resultado encontrado
[139/424] Buscando na TMDB: Evil Under the Sun
[140/424] Buscando na TMDB: Exit to Eden
[141/424] Buscando na TMDB: Factotum
[142/424] Buscando na TMDB: Fahrenheit 451
[143/424] Buscando na TMDB: Fear and Loathing in Las Vegas
[144/424] Buscando na TMDB: Fifty Shades of Grey
[145/424] Buscando na TMDB: Flowers in the Attic
[146/424] Buscando na TMDB: For Your Eyes Only
[147/424] Buscando na TMDB: Forrest Gump
[148/424] Buscando na TMDB: The Fountainhead
[149/424] Buscando na TMDB: From Russia, with Love
[150/424] Buscando na TMDB: Gabriela, Cravo e Canela
[151/424] Buscando na TMDB: The Gadfly
[152/424] Buscando na TMDB: O Gaúcho
[153/424] Buscando na TMDB: Gerald's Game
[154/424] Buscando na TMDB: Goldfinger
[155/424] Buscando na TMDB: The Good Earth
[156/424] Buscando na TMDB: The Graduate
[157/424] Buscando na TMDB: O Grande Gatsby
[158/424] Buscando na TMDB: O Grande Mentecapto
[159/424] Buscando na TMDB: Gruppenbild mit Dame
[160/424] Buscando na TMDB: O Guarani
[161/424] Buscando na TMDB: Hamnet
[162/424] Buscando na TMDB: Harry Potter and the Order of the Phoenix
[163/424] Buscando na TMDB: Harry Potter and the Chamber of Secrets
[164/424] Buscando na TMDB: Harry Potter e a Pedra Filosofal
[165/424] Buscando na TMDB: Harry Potter and the Deathly Hallows
[166/424] Buscando na TMDB: Harry Potter e o Cálice de Fogo
[167/424] Buscando na TMDB: Harry Potter and the Half-Blood Prince
[168/424] Buscando na TMDB: Harry Potter e o Prisioneiro de Azkaban
[169/424] Buscando na TMDB: He's Just Not That Into You
[170/424] Buscando na TMDB: Hodejegerne
[171/424] Buscando na TMDB: Holes
[172/424] Buscando na TMDB: O Homem Duplicado
[173/424] Buscando na TMDB: O Homem Nu
[174/424] Buscando na TMDB: A Hora da Estrela
[175/424] Buscando na TMDB: The Host
[176/424] Buscando na TMDB: Hotaru no Haka
[177/424] Buscando na TMDB: The Hound of Death and Other Stories
  -> nenhum resultado encontrado
[178/424] Buscando na TMDB: The House of the Seven Gables
[179/424] Buscando na TMDB: Howl's Moving Castle
[180/424] Buscando na TMDB: The Human Stain
[181/424] Buscando na TMDB: I Am Legend
[182/424] Buscando na TMDB: I Am Number Four
[183/424] Buscando na TMDB: I Know What You Did Last Summer
[184/424] Buscando na TMDB: I Know Why the Caged Bird Sings
[185/424] Buscando na TMDB: I, Claudius
[186/424] Buscando na TMDB: I'm Thinking of Ending Things
[187/424] Buscando na TMDB: Iaiá Garcia
  -> nenhum resultado encontrado
[188/424] Buscando na TMDB: L'île mystérieuse
[189/424] Buscando na TMDB: Ilhas na Corrente
  -> nenhum resultado encontrado
[190/424] Buscando na TMDB: The Illustrated Man
[191/424] Buscando na TMDB: Im Westen nichts Neues
[192/424] Buscando na TMDB: In der Strafkolonie
  -> nenhum resultado encontrado
[193/424] Buscando na TMDB: Inocência
[194/424] Buscando na TMDB: O Inverno do Nosso Descontentamento
  -> nenhum resultado encontrado
[195/424] Buscando na TMDB: Iracema
[196/424] Buscando na TMDB: Ismael
[197/424] Buscando na TMDB: It
[198/424] Buscando na TMDB: A Jangada de Pedra
[199/424] Buscando na TMDB: The Garden of Eden
[200/424] Buscando na TMDB: O Jardim Secreto
[201/424] Buscando na TMDB: Josefine Mutzenbacher
[202/424] Buscando na TMDB: Jumanji
[203/424] Buscando na TMDB: Justine
[204/424] Buscando na TMDB: Kara no Kyoukai
[205/424] Buscando na TMDB: The Kite Runner
[206/424] Buscando na TMDB: Kleiner Mann – was nun?
[207/424] Buscando na TMDB: L.A. Confidential
[208/424] Buscando na TMDB: L'homme qui plantait des arbres
[209/424] Buscando na TMDB: La invención de Morel
[210/424] Buscando na TMDB: A Lagoa Azul
[211/424] Buscando na TMDB: Last Summer
[212/424] Buscando na TMDB: Laughter in the Dark
[213/424] Buscando na TMDB: Lavoura Arcaica
[214/424] Buscando na TMDB: Le Grand Meaulnes
[215/424] Buscando na TMDB: Le Petit Prince
[216/424] Buscando na TMDB: O Leitor
[217/424] Buscando na TMDB: Les liaisons dangereuses
[218/424] Buscando na TMDB: Life with Father
[219/424] Buscando na TMDB: The Lightning Thief
[220/424] Buscando na TMDB: Live and Let Die
[221/424] Buscando na TMDB: Lolita
[222/424] Buscando na TMDB: The Love of the Last Tycoon
[223/424] Buscando na TMDB: The Lovely Bones
[224/424] Buscando na TMDB: Lúcia McCartney
[225/424] Buscando na TMDB: Lucíola
[226/424] Buscando na TMDB: Lula, o Filho do Brasil
[227/424] Buscando na TMDB: Luzia-Homem
[228/424] Buscando na TMDB: Machenka
[229/424] Buscando na TMDB: Macunaíma
[230/424] Buscando na TMDB: O Mago
[231/424] Buscando na TMDB: Main Street
[232/424] Buscando na TMDB: Malu de Bicicleta
[233/424] Buscando na TMDB: Män som hatar kvinnor
[234/424] Buscando na TMDB: The Man with the Golden Gun
[235/424] Buscando na TMDB: Manhã Transfigurada
[236/424] Buscando na TMDB: Mansfield Park
[237/424] Buscando na TMDB: Manuscrit trouvé à Saragosse
[238/424] Buscando na TMDB: Mãos Vazias
[239/424] Buscando na TMDB: Marley & Eu
[240/424] Buscando na TMDB: A Marquesa d'O
[241/424] Buscando na TMDB: O Matador
[242/424] Buscando na TMDB: Maze Runner: Correr ou Morrer
[243/424] Buscando na TMDB: Memórias do Cárcere
[244/424] Buscando na TMDB: Memórias Póstumas de Brás Cubas
[245/424] Buscando na TMDB: Memórias de uma Gueixa
[246/424] Buscando na TMDB: As Meninas
[247/424] Buscando na TMDB: O Menino Maluquinho
[248/424] Buscando na TMDB: Message in a Bottle
[249/424] Buscando na TMDB: Meu Pé de Laranja Lima
[250/424] Buscando na TMDB: Minha Vida de Menina
[251/424] Buscando na TMDB: Os Miseráveis
[252/424] Buscando na TMDB: Mockingjay
[253/424] Buscando na TMDB: O Monge
[254/424] Buscando na TMDB: Moonraker
[255/424] Buscando na TMDB: A Moreninha
[256/424] Buscando na TMDB: Mortal Engines
[257/424] Buscando na TMDB: Morte em Veneza
[258/424] Buscando na TMDB: Mr. Popper's Penguins
[259/424] Buscando na TMDB: Mudbound
[260/424] Buscando na TMDB: Murder on the Orient Express
[261/424] Buscando na TMDB: My Early Life
  -> nenhum resultado encontrado
[262/424] Buscando na TMDB: Mystic River
[263/424] Buscando na TMDB: Naomi
[264/424] Buscando na TMDB: Lua Nova
[265/424] Buscando na TMDB: No Coração do Mar
[266/424] Buscando na TMDB: No Country for Old Men
[267/424] Buscando na TMDB: Noite
[268/424] Buscando na TMDB: Northern Lights
[269/424] Buscando na TMDB: O Alfaiate do Panamá
[270/424] Buscando na TMDB: O Estranho Misterioso
[271/424] Buscando na TMDB: O Exorcista
[272/424] Buscando na TMDB: O Menino no Espelho
[273/424] Buscando na TMDB: O Tigre e o Dragão
[274/424] Buscando na TMDB: O Velho e o Mar
[275/424] Buscando na TMDB: O Vendedor de Passados
[276/424] Buscando na TMDB: Objeto Quase
  -> nenhum resultado encontrado
[277/424] Buscando na TMDB: A Obra ao Negro
  -> nenhum resultado encontrado
[278/424] Buscando na TMDB: Octopussy and The Living Daylights
  -> nenhum resultado encontrado
[279/424] Buscando na TMDB: Ratos e Homens
[280/424] Buscando na TMDB: On Her Majesty's Secret Service
[281/424] Buscando na TMDB: Ordeal by Innocence
[282/424] Buscando na TMDB: Orgulho e Preconceito
[283/424] Buscando na TMDB: El otoño del patriarca
  -> nenhum resultado encontrado
[284/424] Buscando na TMDB: Pantera no Porão
  -> nenhum resultado encontrado
[285/424] Buscando na TMDB: Os Pastores da Noite
[286/424] Buscando na TMDB: O Pequeno Lord
[287/424] Buscando na TMDB: Perdida
[288/424] Buscando na TMDB: O Perfume
[289/424] Buscando na TMDB: Pergunte ao Pó
[290/424] Buscando na TMDB: The Perks of Being a Wallflower
[291/424] Buscando na TMDB: Pet Sematary
[292/424] Buscando na TMDB: Peter and Wendy
[293/424] Buscando na TMDB: O Picapau Amarelo
[294/424] Buscando na TMDB: Pimpinela Escarlate
[295/424] Buscando na TMDB: La Planète des singes
[296/424] Buscando na TMDB: Pollyanna
[297/424] Buscando na TMDB: Bridge to Terabithia
[298/424] Buscando na TMDB: As Pontes de Madison
[299/424] Buscando na TMDB: Pop. 1280
[300/424] Buscando na TMDB: Por Quem os Sinos Dobram
[301/424] Buscando na TMDB: Postcards from the Edge
[302/424] Buscando na TMDB: The Prince and the Pauper
[303/424] Buscando na TMDB: Procura-se um Marido
[304/424] Buscando na TMDB: Professor Unrat
[305/424] Buscando na TMDB: O Que É Isso, Companheiro?
[306/424] Buscando na TMDB: O Quinze
[307/424] Buscando na TMDB: Riders of the Purple Sage
[308/424] Buscando na TMDB: Rainbow 6
[309/424] Buscando na TMDB: A Rainha Margot
[310/424] Buscando na TMDB: Raise the Titanic!
[311/424] Buscando na TMDB: O Pónei Vermelho
  -> nenhum resultado encontrado
[312/424] Buscando na TMDB: Rei, Dama, Valete
[313/424] Buscando na TMDB: O Retrato de Dorian Gray
[314/424] Buscando na TMDB: Retrato de uma Senhora
[315/424] Buscando na TMDB: Return to Paradise
[316/424] Buscando na TMDB: Ripley Subterrâneo
  -> nenhum resultado encontrado
[317/424] Buscando na TMDB: Rita Hayworth and Shawshank Redemption
  -> nenhum resultado encontrado
[318/424] Buscando na TMDB: Romance dos Três Reinos
  -> nenhum resultado encontrado
[319/424] Buscando na TMDB: Rouge Brésil
[320/424] Buscando na TMDB: The Rum Diary
[321/424] Buscando na TMDB: Rum Punch
  -> nenhum resultado encontrado
[322/424] Buscando na TMDB: The Runaway Jury
  -> nenhum resultado encontrado
[323/424] Buscando na TMDB: The Russia House
[324/424] Buscando na TMDB: S. Bernardo
[325/424] Buscando na TMDB: As Sandálias do Pescador
[326/424] Buscando na TMDB: Sans Famille
[327/424] Buscando na TMDB: Sargento Getúlio
[328/424] Buscando na TMDB: Satíricon
[329/424] Buscando na TMDB: Scarface
[330/424] Buscando na TMDB: The Scarlet Letter
[331/424] Buscando na TMDB: Schindler's Ark
  -> nenhum resultado encontrado
[332/424] Buscando na TMDB: The Sea of Monsters
[333/424] Buscando na TMDB: Seabiscuit: An American Legend
  -> nenhum resultado encontrado
[334/424] Buscando na TMDB: Sem Destino
[335/424] Buscando na TMDB: O Seminarista
[336/424] Buscando na TMDB: Senhora
[337/424] Buscando na TMDB: Sense and Sensibility
[338/424] Buscando na TMDB: O Silêncio da Chuva
[339/424] Buscando na TMDB: Sinhá-Moça
[340/424] Buscando na TMDB: Sítio do Picapau Amarelo
[341/424] Buscando na TMDB: Sob o Sol de Satã
[342/424] Buscando na TMDB: O Som da Montanha
[343/424] Buscando na TMDB: The Sound and the Fury
[344/424] Buscando na TMDB: Spartacus
[345/424] Buscando na TMDB: Stardust
[346/424] Buscando na TMDB: Starter for Ten
[347/424] Buscando na TMDB: Suite française
[348/424] Buscando na TMDB: Sunrise on the Reaping
[349/424] Buscando na TMDB: Die Weber
[350/424] Buscando na TMDB: Tell No One
[351/424] Buscando na TMDB: We Need to Talk About Kevin
[352/424] Buscando na TMDB: And Then There Were None
[353/424] Buscando na TMDB: Tenda dos Milagres
[354/424] Buscando na TMDB: Tender Is the Night
[355/424] Buscando na TMDB: Teresa Filósofa
  -> nenhum resultado encontrado
[356/424] Buscando na TMDB: Ziemia Obiecana
[357/424] Buscando na TMDB: Tess dos d'Urbervilles
  -> nenhum resultado encontrado
[358/424] Buscando na TMDB: Thank You for Smoking
[359/424] Buscando na TMDB: The Body Snatchers
[360/424] Buscando na TMDB: The Case of the Howling Dog
[361/424] Buscando na TMDB: The Constant Gardener
[362/424] Buscando na TMDB: The Cruel Sea
[363/424] Buscando na TMDB: The Death Cure
[364/424] Buscando na TMDB: The Disaster Artist
[365/424] Buscando na TMDB: The Executioners
[366/424] Buscando na TMDB: The Friends of Eddie Coyle
[367/424] Buscando na TMDB: The Handmaid's Tale
[368/424] Buscando na TMDB: The Hate U Give
[369/424] Buscando na TMDB: The Hundred and One Dalmatians
[370/424] Buscando na TMDB: The Hunger Games
[371/424] Buscando na TMDB: The Invention of Hugo Cabret
[372/424] Buscando na TMDB: The Last of the Mohicans
[373/424] Buscando na TMDB: The Little Drummer Girl
[374/424] Buscando na TMDB: The Lost World
[375/424] Buscando na TMDB: The Maltese Falcon
[376/424] Buscando na TMDB: The Mothman Prophecies
[377/424] Buscando na TMDB: The Prisoner of Zenda
[378/424] Buscando na TMDB: The Red Badge of Courage
[379/424] Buscando na TMDB: The Scorch Trials
[380/424] Buscando na TMDB: The Shining
[381/424] Buscando na TMDB: The Sun Also Rises
[382/424] Buscando na TMDB: The Talented Mr. Ripley
[383/424] Buscando na TMDB: The War of the Worlds
[384/424] Buscando na TMDB: The Wettest County in the World
  -> nenhum resultado encontrado
[385/424] Buscando na TMDB: Thérèse Desqueyroux
[386/424] Buscando na TMDB: Thérèse Raquin
[387/424] Buscando na TMDB: Three Act Tragedy
  -> nenhum resultado encontrado
[388/424] Buscando na TMDB: Thunderball
[389/424] Buscando na TMDB: Tieta do Agreste
[390/424] Buscando na TMDB: Tinker Tailor Soldier Spy

In [ ]:
df_tmdb_bruto = pd.DataFrame(resultados_tmdb)

print(df_tmdb_bruto.shape)
df_tmdb_bruto.head(10)

(424, 12)

,titulo_wikipedia,tmdb_id,titulo_tmdb,data_lancamento,idioma_original,generos,duracao_min,orcamento,receita,popularidade,media_votos,contagem_votos
0,Artur e os Minimeus,9992.0,Arthur e os Minimoys,2006-12-13,fr,"Aventura, Fantasia, Animação, Família",94.0,86000000.0,108605609.0,6.5825,6.394,3100.0
1,1 Litre no Namida,41261.0,1リットルの涙,2005-02-05,ja,Drama,98.0,0.0,0.0,1.9354,7.833,36.0
2,84 Charing Cross Road,15677.0,"Nunca Te Vi, Sempre Te Amei",1987-02-13,en,"Drama, Romance",100.0,0.0,2538291.0,2.9330,7.200,232.0
3,2010: Odyssey Two,4437.0,2010: O Ano em que Faremos Contato,1984-12-06,en,"Thriller, Ficção científica",115.0,28000000.0,40400000.0,12.2490,6.662,1117.0
4,3096 Dias,166666.0,3096 Dias de Cativeiro,2013-02-21,de,Drama,111.0,0.0,6677474.0,8.3553,7.398,1022.0
5,A Autobiografia de um Mentiroso: Volume VI,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
6,A Culpa É das Estrelas,222935.0,A Culpa é das Estrelas,2014-06-03,en,"Romance, Drama",132.0,14000000.0,307166834.0,8.7213,7.590,11686.0
7,À Espera de um Milagre,497.0,À Espera de um Milagre,1999-12-10,en,"Fantasia, Drama, Crime",189.0,60000000.0,286801374.0,35.0176,8.506,19795.0
8,A Feiticeira,9722.0,A Feiticeira,2005-06-21,en,"Comédia, Fantasia, Romance",102.0,85000000.0,131426169.0,5.7212,5.091,1689.0
9,A Filosofia na Alcova,486576.0,A Filosofia na Alcova,2017-11-23,pt,Drama,77.0,0.0,0.0,0.9440,5.625,8.0

In [ ]:
# Dado bruto: exatamente como veio da API, sem qualquer limpeza de conteúdo
caminho_csv_tmdb = RAW / "tmdb_resultados.csv"
df_tmdb_bruto.to_csv(caminho_csv_tmdb, index=False, encoding="utf-8")

salvar_proveniencia()  # reescreve o log completo (Wikipedia + Google Books + TMDB)

print(f"Salvo: {caminho_csv_tmdb}")

Proveniência salva em: dados_brutos/proveniencia.json (1216 entradas)
Salvo: dados_brutos/tmdb_resultados.csv

In [ ]:
# Profiling inicial da TMDB (mesmo padrão aplicado ao Google Books)
print("Dimensões:", df_tmdb_bruto.shape)
print("\nTipos de dados:")
print(df_tmdb_bruto.dtypes)

missing_values_tmdb = df_tmdb_bruto.isnull().sum()
print("\nContagem de valores ausentes por coluna:")
print(missing_values_tmdb[missing_values_tmdb > 0])

missing_percentage_tmdb = (df_tmdb_bruto.isnull().sum() / len(df_tmdb_bruto)) * 100
print("\nPorcentagem de valores ausentes por coluna:")
print(missing_percentage_tmdb[missing_percentage_tmdb > 0].sort_values(ascending=False))

taxa_match = df_tmdb_bruto["tmdb_id"].notna().mean() * 100
print(f"\nTaxa de correspondência (título encontrou um filme na TMDB): {taxa_match:.1f}%")

Dimensões: (424, 12)

Tipos de dados:
titulo_wikipedia     object
tmdb_id             float64
titulo_tmdb          object
data_lancamento      object
idioma_original      object
generos              object
duracao_min         float64
orcamento           float64
receita             float64
popularidade        float64
media_votos         float64
contagem_votos      float64
dtype: object

Contagem de valores ausentes por coluna:
tmdb_id            60
titulo_tmdb        60
data_lancamento    66
idioma_original    60
generos            66
duracao_min        60
orcamento          60
receita            60
popularidade       60
media_votos        60
contagem_votos     60
dtype: int64

Porcentagem de valores ausentes por coluna:
data_lancamento    15.566038
generos            15.566038
tmdb_id            14.150943
titulo_tmdb        14.150943
idioma_original    14.150943
duracao_min        14.150943
orcamento          14.150943
receita            14.150943
popularidade       14.150943
media_votos        14.150943
contagem_votos     14.150943
dtype: float64

Taxa de correspondência (título encontrou um filme na TMDB): 85.8%

### Candidatos por consulta às APIs

Antes de partir para a limpeza, registramos quantos resultados cada consulta ao Google Books e
à TMDB retornou. Como o código mantém apenas o primeiro, esta contagem torna visível quantas
edições/candidatos foram descartados, informação para o dataset card.

In [ ]:
# Quantos candidatos cada consulta às APIs devolveu.
# extrair_info() e a busca da TMDB ficam com o primeiro resultado e descartam o resto.
# Recontamos, a partir dos JSONs brutos salvos, quantos candidatos havia por título, tornando visível esse descarte para registrar no dataset card.
def _contar_resultados(pasta, chave_lista, padrao="*.json"):
    contagens = []
    for arq in sorted(Path(pasta).glob(padrao)):
        try:
            payload = json.loads(arq.read_text(encoding="utf-8"))
        except Exception:
            continue
        n = len(payload.get(chave_lista, []) or [])
        contagens.append(n)
    return pd.Series(contagens, name="n_resultados")

for nome, pasta, chave, padrao in [
    ("Google Books", GOOGLEBOOKS_BRUTO, "items",   "*.json"),
    ("TMDB (busca)", TMDB_BRUTO,        "results", "tmdb_busca_*.json"),
]:
    s = _contar_resultados(pasta, chave, padrao)
    if len(s):
        print(f"--- {nome} ---")
        print(f"  consultas com 0 resultados:  {(s == 0).sum()}")
        print(f"  consultas com 1 resultado:   {(s == 1).sum()}")
        print(f"  consultas com >1 resultado:  {(s > 1).sum()}  "
              f"(estas tiveram candidatos descartados por [0])")
        print(f"  máximo de candidatos p/ 1 título: {s.max()}\n")
    else:
        print(f"--- {nome} ---  (nenhum JSON encontrado em {pasta})\n")

--- Google Books ---
  consultas com 0 resultados:  1
  consultas com 1 resultado:   4
  consultas com >1 resultado:  419  (estas tiveram candidatos descartados por [0])
  máximo de candidatos p/ 1 título: 10

--- TMDB (busca) ---
  consultas com 0 resultados:  60
  consultas com 1 resultado:   130
  consultas com >1 resultado:  234  (estas tiveram candidatos descartados por [0])
  máximo de candidatos p/ 1 título: 20

## Limpeza, tratamento e integração das três fontes

Agora que temos os três brutos coletados e preservados (`dados_brutos/`), seguimos o mesmo fluxo
de limpeza usado em aula: **profiling → dados ausentes → duplicatas → tipos → texto → integração →
outliers → validação → salvar**. Nenhuma célula abaixo altera os DataFrames `*_bruto`: sempre
trabalhamos sobre cópias (`.copy()`), preservando a fonte original intocada em memória e em disco.

### 1. Profiling inicial das três fontes brutas

Antes de qualquer decisão de limpeza, olhamos a "cena do crime" nas três tabelas.

In [ ]:
for nome, dframe in [
    ("Wikipédia (livros->filmes)", df_wikipedia_bruto),
    ("Google Books", df_google_books_bruto),
    ("TMDB", df_tmdb_bruto),
]:
    print("=" * 60)
    print(nome)
    print("=" * 60)
    print(f"Dimensões: {dframe.shape}")
    dframe.info()
    print()

============================================================
Wikipédia (livros->filmes)
============================================================
Dimensões: (424, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424 entries, 0 to 423
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   titulo_wikipedia_sujo  424 non-null    object
 1   url_artigo             424 non-null    object
 2   titulo_wikipedia       424 non-null    object
dtypes: object(3)
memory usage: 10.1+ KB

============================================================
Google Books
============================================================
Dimensões: (424, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424 entries, 0 to 423
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   titulo_wikipedia     424 non-null    object
 1   titulo_google_books  423 non-null    object
 2   autor                404 non-null    object
 3   ano_publicacao       413 non-null    object
 4   nota_media           83 non-null     float64
 5   n_avaliacoes         83 non-null     float64
 6   categorias           299 non-null    object
 7   idioma               423 non-null    object
 8   editora              242 non-null    object
dtypes: float64(2), object(7)
memory usage: 29.9+ KB

============================================================
TMDB
============================================================
Dimensões: (424, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424 entries, 0 to 423
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   titulo_wikipedia  424 non-null    object
 1   tmdb_id           364 non-null    float64
 2   titulo_tmdb       364 non-null    object
 3   data_lancamento   358 non-null    object
 4   idioma_original   364 non-null    object
 5   generos           358 non-null    object
 6   duracao_min       364 non-null    float64
 7   orcamento         364 non-null    float64
 8   receita           364 non-null    float64
 9   popularidade      364 non-null    float64
 10  media_votos       364 non-null    float64
 11  contagem_votos    364 non-null    float64
dtypes: float64(7), object(5)
memory usage: 39.9+ KB

### 2. Chave de integração: normalização dos títulos

As três fontes usam `titulo_wikipedia` como referência, mas o texto pode variar levemente entre
fontes (acentuação, caixa, espaços, pontuação residual do scraping). Para o `join` funcionar de
verdade, criamos uma **chave normalizada** (`chave_titulo`): minúsculas, sem acentos, sem pontuação
e sem espaços duplicados. Essa é a mesma ideia de "strip + title/lower" vista em aula para
categóricas sujas, aplicada aqui à chave de integração.

In [ ]:
import unicodedata

def normalizar_titulo(titulo):
    # Gera uma chave de integração robusta a pequenas divergências de grafia:
    # remove acentos, pontuação e normaliza espaços/caixa.
    if pd.isna(titulo):
        return None
    texto = str(titulo).strip().lower()
    texto = unicodedata.normalize("NFKD", texto)
    texto = "".join(c for c in texto if not unicodedata.combining(c))  # remove acentos
    texto = re.sub(r"[^a-z0-9\s]", "", texto)   # remove pontuação/símbolos
    texto = re.sub(r"\s+", " ", texto).strip()  # normaliza espaços
    return texto

# Aplicando a chave nas três fontes (sobre cópias, dados brutos preservados)
df_wikipedia = df_wikipedia_bruto.copy()
df_google_books = df_google_books_bruto.copy()
df_tmdb = df_tmdb_bruto.copy()

for dframe in (df_wikipedia, df_google_books, df_tmdb):
    dframe["chave_titulo"] = dframe["titulo_wikipedia"].apply(normalizar_titulo)

# Checagem: a normalização de fato reduziu variações? (esperado: poucas ou nenhuma mudança
# no wikipedia, já que a chave nasce dele; mas serve de checagem sanitária)
print("Títulos únicos (wikipedia) antes de normalizar:", df_wikipedia_bruto["titulo_wikipedia"].nunique())
print("Chaves únicas (wikipedia) após normalizar:      ", df_wikipedia["chave_titulo"].nunique())

Títulos únicos (wikipedia) antes de normalizar: 424
Chaves únicas (wikipedia) após normalizar:       424

### 2.1 Colisões na chave de integração

Verificamos quais títulos, se houver, colapsam na mesma `chave_titulo` após a normalização,
distinguindo reedições (mesma obra) de homônimos (obras distintas).

In [ ]:

colisoes = (
    df_wikipedia["chave_titulo"]
    .value_counts()
    .loc[lambda s: s > 1]
)
print(f"Chaves com colisão na Wikipédia: {len(colisoes)}")
if len(colisoes):
    print("\nTítulos que colapsam na mesma chave (verificar se são a mesma obra):")
    for chave in colisoes.index:
        titulos = df_wikipedia.loc[
            df_wikipedia["chave_titulo"] == chave, "titulo_wikipedia"
        ].tolist()
        print(f"  [{chave}] -> {titulos}")
else:
    print("Nenhuma colisão: a unicidade vem do desenho da coleta, não desta etapa "
          "(registrar isso honestamente no dataset card).")

Chaves com colisão na Wikipédia: 0
Nenhuma colisão: a unicidade vem do desenho da coleta, não desta etapa (registrar isso honestamente no dataset card).

### 3. Duplicatas

Duplicatas completas (linha idêntica em todas as colunas) e duplicatas na **chave de integração**
são tratadas separadamente: a primeira indica erro de coleta; a segunda pode indicar reedições do
mesmo livro (ex.: capa dura e brochura) que, para este projeto, representam a mesma obra — mantemos
apenas a primeira ocorrência por chave.

In [ ]:
for nome, dframe in [("Wikipédia", df_wikipedia), ("Google Books", df_google_books), ("TMDB", df_tmdb)]:
    dups_completas = dframe.duplicated().sum()
    dups_chave = dframe.duplicated(subset=["chave_titulo"]).sum()
    print(f"{nome:15s} | duplicatas completas: {dups_completas:3d} | duplicatas na chave: {dups_chave:3d}")

# Removendo duplicatas na chave, mantendo a primeira ocorrência
df_wikipedia = df_wikipedia.drop_duplicates(subset=["chave_titulo"], keep="first")
df_google_books = df_google_books.drop_duplicates(subset=["chave_titulo"], keep="first")
df_tmdb = df_tmdb.drop_duplicates(subset=["chave_titulo"], keep="first")

print("\nLinhas após remoção de duplicatas na chave:")
print(f"  Wikipédia:    {len(df_wikipedia)}")
print(f"  Google Books: {len(df_google_books)}")
print(f"  TMDB:         {len(df_tmdb)}")

Wikipédia       | duplicatas completas:   0 | duplicatas na chave:   0
Google Books    | duplicatas completas:   0 | duplicatas na chave:   0
TMDB            | duplicatas completas:   0 | duplicatas na chave:   0

Linhas após remoção de duplicatas na chave:
  Wikipédia:    424
  Google Books: 424
  TMDB:         424

### 4. Correção de tipos de dados

`ano_publicacao` (Google Books) vem em formatos mistos (`"1999"`, `"1999-05-01"`, `"1999-05"`).
`data_lancamento` (TMDB) vem como `"AAAA-MM-DD"`. Extraímos o **ano** de cada um para permitir
comparações numéricas, e convertemos os campos numéricos que a API devolveu como texto/objeto.

In [ ]:
# --- Google Books: extraindo o ano de publicação do livro ---
df_google_books["ano_publicacao_livro"] = pd.to_numeric(
    df_google_books["ano_publicacao"].astype(str).str.extract(r"(\d{4})")[0],
    errors="coerce",
)

df_google_books["nota_media"] = pd.to_numeric(df_google_books["nota_media"], errors="coerce")
df_google_books["n_avaliacoes"] = pd.to_numeric(df_google_books["n_avaliacoes"], errors="coerce")

# --- TMDB: convertendo data de lançamento e extraindo o ano do filme ---
df_tmdb["data_lancamento"] = pd.to_datetime(df_tmdb["data_lancamento"], errors="coerce")
df_tmdb["ano_lancamento_filme"] = df_tmdb["data_lancamento"].dt.year

for coluna in ["duracao_min", "orcamento", "receita", "popularidade", "media_votos", "contagem_votos"]:
    df_tmdb[coluna] = pd.to_numeric(df_tmdb[coluna], errors="coerce")

print("Tipos após correção (Google Books):")
print(df_google_books[["ano_publicacao_livro", "nota_media", "n_avaliacoes"]].dtypes)
print("\nTipos após correção (TMDB):")
print(df_tmdb[["data_lancamento", "ano_lancamento_filme", "orcamento", "receita"]].dtypes)

Tipos após correção (Google Books):
ano_publicacao_livro    float64
nota_media              float64
n_avaliacoes            float64
dtype: object

Tipos após correção (TMDB):
data_lancamento         datetime64[ns]
ano_lancamento_filme           float64
orcamento                      float64
receita                        float64
dtype: object

### 5. Dados ausentes

Cada coluna recebe uma decisão justificada, e não um `fillna(0)` genérico:

- **`tmdb_id` ausente** (título não encontrado na TMDB): mantemos a linha, mas criamos a flag
  `tem_match_tmdb` — remover essas linhas jogaria fora casos legítimos de "livro sem adaptação
  encontrada pela API" (por título divergente, filme muito antigo/obscuro etc.), o que é, em si,
  uma informação relevante para a pergunta motivadora.
- **`nota_media`/`n_avaliacoes` (Google Books) ausentes**: mesma lógica — o livro existe, mas não
  tem avaliação suficiente no Google Books. Mantemos `NaN` (não inventamos uma nota) e criamos a
  flag `tem_avaliacoes_google_books`.
- **`orcamento`/`receita` (TMDB) iguais a 0**: na TMDB, filmes sem esse dado divulgado aparecem
  como `0`, não como ausente — tratamos `0` como "não informado" (`NaN`), para não distorcer médias
  e detecção de outliers.
- **Categóricas textuais ausentes** (`generos`, `idioma_original`, `categorias`, `editora`):
  preenchidas com o rótulo explícito `"Não informado"`, preservando a linha sem fabricar uma
  categoria específica.

In [ ]:
# Flags de correspondência/disponibilidade (antes de qualquer imputação)
df_tmdb["tem_match_tmdb"] = df_tmdb["tmdb_id"].notna()
df_google_books["tem_avaliacoes_google_books"] = df_google_books["n_avaliacoes"].notna()

# Orçamento/receita == 0 na TMDB geralmente significa "não divulgado", não "gratuito"
df_tmdb["orcamento"] = df_tmdb["orcamento"].replace(0, np.nan)
df_tmdb["receita"] = df_tmdb["receita"].replace(0, np.nan)
df_tmdb["duracao_min"] = df_tmdb["duracao_min"].replace(0, np.nan)

# Imputação de categóricas com rótulo explícito
for coluna in ["generos", "idioma_original"]:
    df_tmdb[coluna] = df_tmdb[coluna].fillna("Não informado")

for coluna in ["categorias", "editora", "idioma", "autor"]:
    if coluna in df_google_books.columns:
        df_google_books[coluna] = df_google_books[coluna].fillna("Não informado")

print("Resumo de ausentes após as decisões acima:\n")
for nome, dframe in [("Google Books", df_google_books), ("TMDB", df_tmdb)]:
    nulos = dframe.isnull().sum()
    print(f"--- {nome} ---")
    print(nulos[nulos > 0])
    print()

Resumo de ausentes após as decisões acima:

--- Google Books ---
titulo_google_books       1
ano_publicacao           11
nota_media              341
n_avaliacoes            341
ano_publicacao_livro     13
dtype: int64

--- TMDB ---
tmdb_id                  60
titulo_tmdb              60
data_lancamento          66
duracao_min              69
orcamento               231
receita                 228
popularidade             60
media_votos              60
contagem_votos           60
ano_lancamento_filme     66
dtype: int64

### 6. Outliers (bilheteria, orçamento e número de avaliações)

Dados de bilheteria/orçamento são naturalmente assimétricos: a maioria dos filmes fatura pouco e
uma minoria de blockbusters puxa a média para cima — isso não é "erro", é a distribuição real do
mercado de cinema. Por isso, **detectamos** os outliers com o método IQR (mesma técnica da aula),
mas a decisão aqui é **não aplicar capping** aos valores financeiros: um blockbuster de verdade é
um dado real e relevante para a pergunta motivadora ("livros populares viram filmes populares?").
Documentamos a detecção para justificar essa escolha no dataset card.

In [ ]:
def detectar_outliers_iqr(serie):
    # Retorna a máscara booleana de outliers e os limites, pelo método IQR clássico.
    dados_validos = serie.dropna()
    q1 = dados_validos.quantile(0.25)
    q3 = dados_validos.quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr
    mascara = (serie < limite_inferior) | (serie > limite_superior)
    return mascara.fillna(False), limite_inferior, limite_superior


for nome_coluna, dframe in [
    ("n_avaliacoes", df_google_books),
    ("receita", df_tmdb),
    ("orcamento", df_tmdb),
    ("popularidade", df_tmdb),
]:
    mascara, lim_inf, lim_sup = detectar_outliers_iqr(dframe[nome_coluna])
    print(
        f"{nome_coluna:15s} | limites IQR: [{lim_inf:,.1f}, {lim_sup:,.1f}] "
        f"| outliers: {mascara.sum()} de {dframe[nome_coluna].notna().sum()} valores válidos"
    )

n_avaliacoes    | limites IQR: [-8.0, 16.0] | outliers: 13 de 83 valores válidos
receita         | limites IQR: [-218,151,859.4, 392,319,765.6] | outliers: 23 de 196 valores válidos
orcamento       | limites IQR: [-72,000,000.0, 139,200,000.0] | outliers: 10 de 193 valores válidos
popularidade    | limites IQR: [-9.2, 18.9] | outliers: 31 de 364 valores válidos

### 7. Integração (join) das três fontes

A chave de integração é `chave_titulo` (título normalizado). Usamos `how="left"` a partir da
Wikipédia — ela é o "esqueleto" da base (todo livro adaptado que encontramos na categoria), e as
outras duas fontes o enriquecem. Linhas sem correspondência ficam com `NaN` nas colunas daquela
fonte, e já sinalizadas pelas flags criadas no passo 5.

In [ ]:
colunas_wikipedia = ["chave_titulo", "titulo_wikipedia", "url_artigo"]
colunas_google_books = [
    "chave_titulo", "titulo_google_books", "autor", "ano_publicacao_livro",
    "nota_media", "n_avaliacoes", "categorias", "idioma", "editora",
    "tem_avaliacoes_google_books",
]
colunas_tmdb = [
    "chave_titulo", "titulo_tmdb", "data_lancamento", "ano_lancamento_filme",
    "idioma_original", "generos", "duracao_min", "orcamento", "receita",
    "popularidade", "media_votos", "contagem_votos", "tem_match_tmdb",
]

df_integrado = (
    df_wikipedia[colunas_wikipedia]
    .merge(df_google_books[colunas_google_books], on="chave_titulo", how="left")
    .merge(df_tmdb[colunas_tmdb], on="chave_titulo", how="left")
)

# Linhas que vieram sem nenhuma correspondência na Google Books recebem tem_avaliacoes_google_books=False
df_integrado["tem_avaliacoes_google_books"] = df_integrado["tem_avaliacoes_google_books"].fillna(False)
df_integrado["tem_match_tmdb"] = df_integrado["tem_match_tmdb"].fillna(False)

print("Dimensões da base integrada:", df_integrado.shape)
df_integrado.head(10)

Dimensões da base integrada: (424, 24)

,chave_titulo,titulo_wikipedia,url_artigo,titulo_google_books,autor,ano_publicacao_livro,nota_media,n_avaliacoes,categorias,idioma,...,ano_lancamento_filme,idioma_original,generos,duracao_min,orcamento,receita,popularidade,media_votos,contagem_votos,tem_match_tmdb
0,artur e os minimeus,Artur e os Minimeus,https://pt.wikipedia.org/wiki/Artur_e_os_Minim...,Arthur and the Minimoys,Luc Besson,2006.0,4.0,1.0,Juvenile Fiction,en,...,2006.0,fr,"Aventura, Fantasia, Animação, Família",94.0,86000000.0,108605609.0,6.5825,6.394,3100.0,True
1,1 litre no namida,1 Litre no Namida,https://pt.wikipedia.org/wiki/1_Litre_no_Namid...,1 Litre of Tears,Kito Aya,2024.0,NaN,NaN,Biography & Autobiography,vi,...,2005.0,ja,Drama,98.0,NaN,NaN,1.9354,7.833,36.0,True
2,84 charing cross road,84 Charing Cross Road,https://pt.wikipedia.org/wiki/84_Charing_Cross...,"84, Charing Cross Road",Helene Hanff,2027.0,NaN,NaN,Literary Collections,en,...,1987.0,en,"Drama, Romance",100.0,NaN,2538291.0,2.9330,7.200,232.0,True
3,2010 odyssey two,2010: Odyssey Two,https://pt.wikipedia.org/wiki/2010:_Odyssey_Two,2010: Odyssey Two,Arthur C. Clarke,1984.0,4.0,18.0,Fiction,en,...,1984.0,en,"Thriller, Ficção científica",115.0,28000000.0,40400000.0,12.2490,6.662,1117.0,True
4,3096 dias,3096 Dias,https://pt.wikipedia.org/wiki/3096_Dias,"3,096 Days","Natascha Kampusch, Heike Gronemeier, Corinna M...",2010.0,NaN,NaN,Biography & Autobiography,en,...,2013.0,de,Drama,111.0,NaN,6677474.0,8.3553,7.398,1022.0,True
5,a autobiografia de um mentiroso volume vi,A Autobiografia de um Mentiroso: Volume VI,https://pt.wikipedia.org/wiki/A_Autobiografia_...,Vi-a Mais Sacra,Melkyzedek Siqueira César,2024.0,NaN,NaN,Biography & Autobiography,pt-BR,...,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False
6,a culpa e das estrelas,A Culpa É das Estrelas,https://pt.wikipedia.org/wiki/A_Culpa_%C3%89_d...,A Culpa Não É Das Estrelas,Daniel Carlos,2022.0,NaN,NaN,Education,pt-BR,...,2014.0,en,"Romance, Drama",132.0,14000000.0,307166834.0,8.7213,7.590,11686.0,True
7,a espera de um milagre,À Espera de um Milagre,https://pt.wikipedia.org/wiki/%C3%80_Espera_de...,À Espera Da Extraordinária Cura,Marinalva Irenice Conceição; Guilherme Do Espí...,2025.0,NaN,NaN,Humor,pt-BR,...,1999.0,en,"Fantasia, Drama, Crime",189.0,60000000.0,286801374.0,35.0176,8.506,19795.0,True
8,a feiticeira,A Feiticeira,https://pt.wikipedia.org/wiki/A_Feiticeira_(li...,"Winnie, a Feiticeira","Korky Paul, Valerie Thomas",1998.0,NaN,NaN,Cats,pt-BR,...,2005.0,en,"Comédia, Fantasia, Romance",102.0,85000000.0,131426169.0,5.7212,5.091,1689.0,True
9,a filosofia na alcova,A Filosofia na Alcova,https://pt.wikipedia.org/wiki/A_Filosofia_na_A...,"Filosofia na Alcôva, A",marquis de Sade,2000.0,5.0,1.0,Fiction,pt-BR,...,2017.0,pt,Drama,77.0,NaN,NaN,0.9440,5.625,8.0,True

### 7.1 Validação da confiabilidade do casamento

O join une as fontes por título, mas isso não garante que livro e filme sejam a mesma obra.
Medimos a similaridade entre os títulos e a coerência de datas para marcar, em `match_confiavel`,
quais linhas podem ser usadas com segurança quando a precisão do casamento for crítica.

In [ ]:
# Validação da confiabilidade do casamento entre as fontes.
# O join casa por título normalizado, mas o primeiro resultado de cada API pode não ser a mesma
# obra (homônimos, traduções, reedições). Sem alterar o join, criamos evidências de confiança:
# similaridade entre os títulos das fontes e coerência de anos, consolidadas na flag match_confiavel.
try:
    from rapidfuzz import fuzz
except ImportError:
    !pip install rapidfuzz -q
    from rapidfuzz import fuzz

def _sim(a, b):
    # Similaridade 0–100 robusta a ordem de palavras; None quando falta título.
    if pd.isna(a) or pd.isna(b):
        return np.nan
    return fuzz.token_sort_ratio(str(a).lower(), str(b).lower())

# Similaridade título-a-título contra a Wikipédia (o esqueleto)
df_integrado["sim_titulo_gb"]   = df_integrado.apply(
    lambda r: _sim(r["titulo_wikipedia"], r["titulo_google_books"]), axis=1)
df_integrado["sim_titulo_tmdb"] = df_integrado.apply(
    lambda r: _sim(r["titulo_wikipedia"], r["titulo_tmdb"]), axis=1)

# Coerência de anos: um livro adaptado costuma ser publicado ANTES do filme.
# Tolerância de +3 anos cobre reedições/novelizações próximas ao lançamento.
df_integrado["ano_coerente"] = (
    df_integrado["ano_publicacao_livro"] <= df_integrado["ano_lancamento_filme"] + 3
)

# Flag final: TMDB casou, título do filme razoavelmente parecido, e ano coerente.
# (o lado Google Books entra como reforço, não como bloqueio, pois tem cobertura baixa)
LIMIAR_SIM = 60
df_integrado["match_confiavel"] = (
    df_integrado["tem_match_tmdb"]
    & (df_integrado["sim_titulo_tmdb"] >= LIMIAR_SIM)
    & (df_integrado["ano_coerente"].fillna(True))  # sem ano do livro, não penaliza
)

print("Taxa de match confiável: "
      f"{df_integrado['match_confiavel'].mean()*100:.1f}%  "
      f"({df_integrado['match_confiavel'].sum()} de {len(df_integrado)})")
print("\nDistribuição da similaridade de título (TMDB):")
print(df_integrado["sim_titulo_tmdb"].describe())

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 34.5 MB/s eta 0:00:00
Taxa de match confiável: 21.7%  (92 de 424)

Distribuição da similaridade de título (TMDB):
count    364.000000
mean      67.739434
std       31.014593
min        0.000000
25%       38.844086
50%       68.432056
75%      100.000000
max      100.000000
Name: sim_titulo_tmdb, dtype: float64

### 8. Engenharia de features

Duas variáveis derivadas, diretamente ligadas às perguntas motivadoras do projeto:

- **`anos_ate_adaptacao`**: quanto tempo (em anos) passou entre a publicação do livro e o
  lançamento do filme. Só é calculável quando ambas as datas existem.
- **`retorno_financeiro`**: proporção `(receita - orçamento) / orçamento`, quando o orçamento é
  conhecido e positivo — uma medida de desempenho comercial do filme.

In [ ]:
df_integrado["retorno_financeiro"] = np.where(
    df_integrado["orcamento"] > 0,
    (df_integrado["receita"] - df_integrado["orcamento"]) / df_integrado["orcamento"],
    np.nan,
)

display(df_integrado[["titulo_wikipedia", "retorno_financeiro"]].describe())

       retorno_financeiro
count        1.770000e+02
mean         1.413008e+04
std          1.879110e+05
min         -9.822581e-01
25%          4.400000e-01
50%          2.219957e+00
75%          6.125000e+00
max          2.499999e+06

### 9. Validação final e comparação bruto × tratado

Fechamos com o "recibo" da limpeza: dimensões, tipos e contagem de nulos antes/depois, por fonte.

In [ ]:
print("=" * 60)
print("RESUMO POR FONTE (bruto -> após limpeza/join)")
print("=" * 60)
print(f"Wikipédia:    {df_wikipedia_bruto.shape[0]:>4} linhas brutas -> {df_wikipedia.shape[0]:>4} após dedup. de chave")
print(f"Google Books: {df_google_books_bruto.shape[0]:>4} linhas brutas -> {df_google_books.shape[0]:>4} após dedup. de chave")
print(f"TMDB:         {df_tmdb_bruto.shape[0]:>4} linhas brutas -> {df_tmdb.shape[0]:>4} após dedup. de chave")

print("\n" + "=" * 60)
print("BASE INTEGRADA FINAL")
print("=" * 60)
print(f"Dimensões:              {df_integrado.shape}")
print(f"Taxa de match TMDB:     {df_integrado['tem_match_tmdb'].mean() * 100:.1f}%")
print(f"Taxa c/ nota Google Books: {df_integrado['tem_avaliacoes_google_books'].mean() * 100:.1f}%")
print("\nValores ausentes por coluna:")
print(df_integrado.isnull().sum().sort_values(ascending=False))

============================================================
RESUMO POR FONTE (bruto -> após limpeza/join)
============================================================
Wikipédia:     424 linhas brutas ->  424 após dedup. de chave
Google Books:  424 linhas brutas ->  424 após dedup. de chave
TMDB:          424 linhas brutas ->  424 após dedup. de chave

============================================================
BASE INTEGRADA FINAL
============================================================
Dimensões:              (424, 29)
Taxa de match TMDB:     85.8%
Taxa c/ nota Google Books: 19.6%

Valores ausentes por coluna:
nota_media                     341
n_avaliacoes                   341
retorno_financeiro             247
orcamento                      231
receita                        228
duracao_min                     69
ano_lancamento_filme            66
data_lancamento                 66
media_votos                     60
popularidade                    60
titulo_tmdb                     60
contagem_votos                  60
sim_titulo_tmdb                 60
ano_publicacao_livro            13
titulo_google_books              1
sim_titulo_gb                    1
categorias                       0
chave_titulo                     0
titulo_wikipedia                 0
url_artigo                       0
autor                            0
tem_avaliacoes_google_books      0
editora                          0
idioma                           0
generos                          0
idioma_original                  0
tem_match_tmdb                   0
ano_coerente                     0
match_confiavel                  0
dtype: int64

### 9.1 Validação de sanidade da base final

Conferência automática de que os valores estão em faixas plausíveis (notas, anos, durações,
valores financeiros) antes de salvar. Não interrompe a execução: lista todas as checagens.

In [ ]:

def checar(condicao_ok, descricao):
    n_falhas = (~condicao_ok).sum()
    status = "OK " if n_falhas == 0 else f"FALHOU ({n_falhas} linhas)"
    print(f"[{status}] {descricao}")

d = df_integrado
print("Validação de faixas (linhas com valor presente):\n")
checar(d["nota_media"].dropna().between(0, 5).reindex(d.index, fill_value=True),
       "nota_media entre 0 e 5")
checar(d["media_votos"].dropna().between(0, 10).reindex(d.index, fill_value=True),
       "media_votos (TMDB) entre 0 e 10")
checar((d["receita"].fillna(0) >= 0),
       "receita não-negativa")
checar((d["orcamento"].fillna(0) >= 0),
       "orcamento não-negativo")
checar(d["ano_lancamento_filme"].dropna().between(1888, 2027).reindex(d.index, fill_value=True),
       "ano do filme entre 1888 (1º filme) e 2027")
checar(d["ano_publicacao_livro"].dropna().between(1400, 2027).reindex(d.index, fill_value=True),
       "ano do livro entre 1400 e 2027")
checar(d["duracao_min"].dropna().between(1, 600).reindex(d.index, fill_value=True),
       "duração entre 1 e 600 min")

print(f"\nDimensões finais: {d.shape}")
print(f"Colunas: {list(d.columns)}")

Validação de faixas (linhas com valor presente):

[OK ] nota_media entre 0 e 5
[OK ] media_votos (TMDB) entre 0 e 10
[OK ] receita não-negativa
[OK ] orcamento não-negativo
[OK ] ano do filme entre 1888 (1º filme) e 2027
[OK ] ano do livro entre 1400 e 2027
[OK ] duração entre 1 e 600 min

Dimensões finais: (424, 29)
Colunas: ['chave_titulo', 'titulo_wikipedia', 'url_artigo', 'titulo_google_books', 'autor', 'ano_publicacao_livro', 'nota_media', 'n_avaliacoes', 'categorias', 'idioma', 'editora', 'tem_avaliacoes_google_books', 'titulo_tmdb', 'data_lancamento', 'ano_lancamento_filme', 'idioma_original', 'generos', 'duracao_min', 'orcamento', 'receita', 'popularidade', 'media_votos', 'contagem_votos', 'tem_match_tmdb', 'sim_titulo_gb', 'sim_titulo_tmdb', 'ano_coerente', 'match_confiavel', 'retorno_financeiro']

9.2 Dicionário de variáveis (dataset card A.3)
Ficha padronizada da base tratada, uma linha por variável. Também exportada para dados_tratados/dicionario_variaveis.csv, para compor o dataset card.

In [ ]:

dicionario = [
    ("chave_titulo",        "texto",             "Título normalizado (sem acento/caixa/pontuação) usado como chave de integração", "-"),
    ("titulo_wikipedia",    "texto",             "Título da obra como listado na categoria da Wikipédia", "-"),
    ("url_artigo",          "texto",             "URL do artigo na Wikipédia (atribuição da fonte)", "-"),
    ("titulo_google_books", "texto",             "Título do livro conforme a Google Books API", "-"),
    ("autor",               "categórica",        "Autor(es) do livro (Google Books)", "-"),
    ("ano_publicacao_livro","numérica discreta", "Ano de publicação da edição retornada pelo Google Books", "ano"),
    ("nota_media",          "numérica contínua", "Nota média do livro no Google Books", "escala 0–5"),
    ("n_avaliacoes",        "numérica discreta", "Número de avaliações do livro no Google Books", "contagem"),
    ("categorias",          "categórica",        "Categorias/gêneros do livro (Google Books)", "-"),
    ("idioma",              "categórica",        "Idioma da edição do livro (Google Books)", "-"),
    ("editora",             "categórica",        "Editora do livro (Google Books)", "-"),
    ("tem_avaliacoes_google_books", "booleana",  "Indica se o livro tem avaliação no Google Books", "-"),
    ("titulo_tmdb",         "texto",             "Título do filme conforme a TMDB", "-"),
    ("data_lancamento",     "data/hora",         "Data de lançamento do filme (TMDB)", "data"),
    ("ano_lancamento_filme","numérica discreta", "Ano de lançamento do filme (derivado de data_lancamento)", "ano"),
    ("idioma_original",     "categórica",        "Idioma original do filme (TMDB)", "-"),
    ("generos",             "categórica",        "Gêneros do filme (TMDB)", "-"),
    ("duracao_min",         "numérica contínua", "Duração do filme (0 tratado como não divulgado -> NaN)", "minutos"),
    ("orcamento",           "numérica contínua", "Orçamento do filme (0 tratado como não divulgado -> NaN)", "USD nominal"),
    ("receita",             "numérica contínua", "Receita/bilheteria do filme (0 -> NaN)", "USD nominal"),
    ("popularidade",        "numérica contínua", "Índice de popularidade da TMDB", "score TMDB"),
    ("media_votos",         "numérica contínua", "Nota média do filme na TMDB", "escala 0–10"),
    ("contagem_votos",      "numérica discreta", "Número de votos do filme na TMDB", "contagem"),
    ("tem_match_tmdb",      "booleana",          "Indica se o título encontrou um filme na TMDB", "-"),
    ("sim_titulo_gb",       "numérica contínua", "Similaridade (0–100) entre título do livro (Google Books) e da Wikipédia", "score 0–100"),
    ("sim_titulo_tmdb",     "numérica contínua", "Similaridade (0–100) entre título do filme (TMDB) e da Wikipédia", "score 0–100"),
    ("ano_coerente",        "booleana",          "True se o livro foi publicado até 3 anos após o filme (coerência de datas)", "-"),
    ("match_confiavel",     "booleana",          "Match validado: TMDB casou + título similar + ano coerente", "-"),
    ("retorno_financeiro",  "numérica contínua", "(receita - orçamento) / orçamento, quando orçamento > 0", "razão"),
]
df_dicionario = pd.DataFrame(dicionario, columns=["Variável", "Tipo", "Descrição", "Unidade"])
# Confere se cobre exatamente as colunas da base (evita esquecer/sobrar coluna)
faltando = set(df_integrado.columns) - set(df_dicionario["Variável"])
sobrando = set(df_dicionario["Variável"]) - set(df_integrado.columns)
if faltando:
    print("ATENÇÃO — colunas na base sem entrada no dicionário:", faltando)
if sobrando:
    print("ATENÇÃO — entradas no dicionário que não existem na base:", sobrando)
if not faltando and not sobrando:
    print("Dicionário cobre exatamente as", len(df_integrado.columns), "colunas da base.")
df_dicionario.to_csv(TRATADO / "dicionario_variaveis.csv", index=False, encoding="utf-8")
display(df_dicionario)

Dicionário cobre exatamente as 29 colunas da base.

,Variável,Tipo,Descrição,Unidade
0,chave_titulo,texto,Título normalizado (sem acento/caixa/pontuação...,-
1,titulo_wikipedia,texto,Título da obra como listado na categoria da Wi...,-
2,url_artigo,texto,URL do artigo na Wikipédia (atribuição da fonte),-
3,titulo_google_books,texto,Título do livro conforme a Google Books API,-
4,autor,categórica,Autor(es) do livro (Google Books),-
5,ano_publicacao_livro,numérica discreta,Ano de publicação da edição retornada pelo Goo...,ano
6,nota_media,numérica contínua,Nota média do livro no Google Books,escala 0–5
7,n_avaliacoes,numérica discreta,Número de avaliações do livro no Google Books,contagem
8,categorias,categórica,Categorias/gêneros do livro (Google Books),-
9,idioma,categórica,Idioma da edição do livro (Google Books),-
10,editora,categórica,Editora do livro (Google Books),-
11,tem_avaliacoes_google_books,booleana,Indica se o livro tem avaliação no Google Books,-
12,titulo_tmdb,texto,Título do filme conforme a TMDB,-
13,data_lancamento,data/hora,Data de lançamento do filme (TMDB),data
14,ano_lancamento_filme,numérica discreta,Ano de lançamento do filme (derivado de data_l...,ano
15,idioma_original,categórica,Idioma original do filme (TMDB),-
16,generos,categórica,Gêneros do filme (TMDB),-
17,duracao_min,numérica contínua,Duração do filme (0 tratado como não divulgado...,minutos
18,orcamento,numérica contínua,Orçamento do filme (0 tratado como não divulga...,USD nominal
19,receita,numérica contínua,Receita/bilheteria do filme (0 -> NaN),USD nominal
20,popularidade,numérica contínua,Índice de popularidade da TMDB,score TMDB
21,media_votos,numérica contínua,Nota média do filme na TMDB,escala 0–10
22,contagem_votos,numérica discreta,Número de votos do filme na TMDB,contagem
23,tem_match_tmdb,booleana,Indica se o título encontrou um filme na TMDB,-
24,sim_titulo_gb,numérica contínua,Similaridade (0–100) entre título do livro (Go...,score 0–100
25,sim_titulo_tmdb,numérica contínua,Similaridade (0–100) entre título do filme (TM...,score 0–100
26,ano_coerente,booleana,True se o livro foi publicado até 3 anos após ...,-
27,match_confiavel,booleana,Match validado: TMDB casou + título similar + ...,-
28,retorno_financeiro,numérica contínua,"(receita - orçamento) / orçamento, quando orça...",razão

In [ ]:
# Salvando a base tratada (integrada e limpa) — separada do bruto, que segue intocado em dados_brutos/
caminho_csv_tratado = TRATADO / "base_livros_filmes_tratada.csv"
df_integrado.to_csv(caminho_csv_tratado, index=False, encoding="utf-8")

# Parquet é o formato preferencial pedido no enunciado (preserva tipos, mais compacto)
caminho_parquet_tratado = TRATADO / "base_livros_filmes_tratada.parquet"
df_integrado.to_parquet(caminho_parquet_tratado, index=False)

salvar_proveniencia()

print(f"Salvo: {caminho_csv_tratado}")
print(f"Salvo: {caminho_parquet_tratado}")

# Prova de que os dados brutos continuam intocados
print("\nBrutos preservados e intocados:")
print(f"  df_wikipedia_bruto:    {df_wikipedia_bruto.shape}")
print(f"  df_google_books_bruto: {df_google_books_bruto.shape}")
print(f"  df_tmdb_bruto:         {df_tmdb_bruto.shape}")

Proveniência salva em: dados_brutos/proveniencia.json (1216 entradas)
Salvo: dados_tratados/base_livros_filmes_tratada.csv
Salvo: dados_tratados/base_livros_filmes_tratada.parquet

Brutos preservados e intocados:
  df_wikipedia_bruto:    (424, 3)
  df_google_books_bruto: (424, 9)
  df_tmdb_bruto:         (424, 12)

### 10. Visualização completa da base tratada

Exibindo a base tratada por inteiro (todas as linhas e colunas), para conferência final antes de
seguir para as próximas fases da disciplina.

In [ ]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)

df_integrado

,chave_titulo,titulo_wikipedia,url_artigo,titulo_google_books,autor,ano_publicacao_livro,nota_media,n_avaliacoes,categorias,idioma,editora,tem_avaliacoes_google_books,titulo_tmdb,data_lancamento,ano_lancamento_filme,idioma_original,generos,duracao_min,orcamento,receita,popularidade,media_votos,contagem_votos,tem_match_tmdb,sim_titulo_gb,sim_titulo_tmdb,ano_coerente,match_confiavel,retorno_financeiro
0,artur e os minimeus,Artur e os Minimeus,https://pt.wikipedia.org/wiki/Artur_e_os_Minim...,Arthur and the Minimoys,Luc Besson,2006.0,4.0,1.0,Juvenile Fiction,en,Harper Collins,True,Arthur e os Minimoys,2006-12-13,2006.0,fr,"Aventura, Fantasia, Animação, Família",94.0,86000000.0,1.086056e+08,6.5825,6.394,3100.0,True,61.904762,87.179487,True,True,2.628559e-01
1,1 litre no namida,1 Litre no Namida,https://pt.wikipedia.org/wiki/1_Litre_no_Namid...,1 Litre of Tears,Kito Aya,2024.0,NaN,NaN,Biography & Autobiography,vi,Não informado,False,1リットルの涙,2005-02-05,2005.0,ja,Drama,98.0,NaN,NaN,1.9354,7.833,36.0,True,54.545455,8.333333,False,False,NaN
2,84 charing cross road,84 Charing Cross Road,https://pt.wikipedia.org/wiki/84_Charing_Cross...,"84, Charing Cross Road",Helene Hanff,2027.0,NaN,NaN,Literary Collections,en,Penguin Classics,False,"Nunca Te Vi, Sempre Te Amei",1987-02-13,1987.0,en,"Drama, Romance",100.0,NaN,2.538291e+06,2.9330,7.200,232.0,True,97.674419,25.000000,False,False,NaN
3,2010 odyssey two,2010: Odyssey Two,https://pt.wikipedia.org/wiki/2010:_Odyssey_Two,2010: Odyssey Two,Arthur C. Clarke,1984.0,4.0,18.0,Fiction,en,Del Rey,True,2010: O Ano em que Faremos Contato,1984-12-06,1984.0,en,"Thriller, Ficção científica",115.0,28000000.0,4.040000e+07,12.2490,6.662,1117.0,True,100.000000,39.215686,True,False,4.428571e-01
4,3096 dias,3096 Dias,https://pt.wikipedia.org/wiki/3096_Dias,"3,096 Days","Natascha Kampusch, Heike Gronemeier, Corinna M...",2010.0,NaN,NaN,Biography & Autobiography,en,Penguin UK,False,3096 Dias de Cativeiro,2013-02-21,2013.0,de,Drama,111.0,NaN,6.677474e+06,8.3553,7.398,1022.0,True,84.210526,58.064516,True,False,NaN
5,a autobiografia de um mentiroso volume vi,A Autobiografia de um Mentiroso: Volume VI,https://pt.wikipedia.org/wiki/A_Autobiografia_...,Vi-a Mais Sacra,Melkyzedek Siqueira César,2024.0,NaN,NaN,Biography & Autobiography,pt-BR,Clube de Autores,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,28.070175,NaN,False,False,NaN
6,a culpa e das estrelas,A Culpa É das Estrelas,https://pt.wikipedia.org/wiki/A_Culpa_%C3%89_d...,A Culpa Não É Das Estrelas,Daniel Carlos,2022.0,NaN,NaN,Education,pt-BR,Clube de Autores,False,A Culpa é das Estrelas,2014-06-03,2014.0,en,"Romance, Drama",132.0,14000000.0,3.071668e+08,8.7213,7.590,11686.0,True,91.666667,100.000000,False,False,2.094049e+01
7,a espera de um milagre,À Espera de um Milagre,https://pt.wikipedia.org/wiki/%C3%80_Espera_de...,À Espera Da Extraordinária Cura,Marinalva Irenice Conceição; Guilherme Do Espí...,2025.0,NaN,NaN,Humor,pt-BR,Clube de Autores,False,À Espera de um Milagre,1999-12-10,1999.0,en,"Fantasia, Drama, Crime",189.0,60000000.0,2.868014e+08,35.0176,8.506,19795.0,True,49.056604,100.000000,False,False,3.780023e+00
8,a feiticeira,A Feiticeira,https://pt.wikipedia.org/wiki/A_Feiticeira_(li...,"Winnie, a Feiticeira","Korky Paul, Valerie Thomas",1998.0,NaN,NaN,Cats,pt-BR,Martins Martins Fontes,False,A Feiticeira,2005-06-21,2005.0,en,"Comédia, Fantasia, Romance",102.0,85000000.0,1.314262e+08,5.7212,5.091,1689.0,True,75.000000,100.000000,True,True,5.461902e-01
9,a filosofia na alcova,A Filosofia na Alcova,https://pt.wikipedia.org/wiki/A_Filosofia_na_A...,"Filosofia na Alcôva, A",marquis de Sade,2000.0,5.0,1.0,Fiction,pt-BR,Editora Iluminuras Ltda,True,A Filosofia na Alcova,2017-11-23,2017.0,pt,Drama,77.0,NaN,NaN,0.9440,5.625,8.0,True,93.023256,100.000000,True,True,NaN
10,a guerra dos mundos,A Guerra dos Mundos,https://pt.wikipedia.org/wiki/A_Guerra_dos_Mundos,Workbook/Lab Manual Part A to Accompany DOS Mu...,"Tracy D. Terrell, Magdalena Andrade, Jeanne Eg...",2001.0,NaN,NaN,Foreign Language Study,en,"McGraw-Hill Humanities, Social Sciences & Worl...",False,A Guerra dos Mundos,2025-07-29,2025.0,en,"Ficção científica, Thriller",90.0,10000000.0,NaN,90.0166,4.016,1130.0,True,43.478261,100.000000,True,True,NaN
11,a incendiaria,A Incendiária,https://pt.wikipedia.org/wiki/A_Incendi%C3%A1ria,A incendiária,Stephen King,2018.0,NaN,NaN,Fiction,pt-BR,Suma,False,Incendiary Blonde,1945-07-25,1945.0,en,"Música, Romance",113.0,NaN,NaN,1.3670,5.111,9.0,True,100.000000,60.000000,False,False,NaN
12,a little princess,A Little Princess,https://pt.wikipedia.org/wiki/A_Little_Princess,A Little Princess,Frances Hodgson Burnett,2020.0,NaN,NaN,Juvenile Fiction,en,Graphic Arts Books,False,A Princesinha,1995-05-10,1995.0,en,"Drama, Família, Fantasia",97.0,17000000.0,1.000000e+07,4.5081,7.639,1072.0,True,100.000000,60.000000,False,False,-4.117647e-01
13,a most wanted man,A Most Wanted Man,https://pt.wikipedia.org/wiki/A_Most_Wanted_Man,A Most Wanted Man,John le Carre,2014.0,NaN,NaN,Fiction,en,Simon and Schuster,False,O Homem Mais Procurado,2014-07-25,2014.0,en,Thriller,122.0,15000000.0,3.155486e+07,4.6723,6.468,1526.0,True,100.000000,41.025641,True,False,1.103657e+00
14,a sangue frio,A Sangue Frio,https://pt.wikipedia.org/wiki/A_Sangue_Frio,A sangue frio,Truman Capote,2003.0,NaN,NaN,True Crime,pt-BR,Editora Companhia das Letras,False,A Sangue Frio,1967-12-15,1967.0,en,"Crime, Drama, História",134.0,3500000.0,1.300755e+07,3.9454,7.521,449.0,True,100.000000,100.000000,False,False,2.716443e+00
15,a venus das peles,A Vênus das Peles,https://pt.wikipedia.org/wiki/A_V%C3%AAnus_das...,A Vênus das peles [Bolso],Leopold Von Sacher-Masoch,2008.0,NaN,NaN,Fiction,pt-BR,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,80.952381,NaN,False,False,NaN
16,about a boy,About a Boy,https://pt.wikipedia.org/wiki/About_a_Boy,About a Boy,Nick Hornby,1999.0,4.0,6.0,Fiction,en,Penguin,True,Um Grande Garoto,2002-04-26,2002.0,en,"Drama, Comédia, Romance",101.0,27000000.0,1.290000e+08,5.6108,6.699,2462.0,True,100.000000,29.629630,True,False,3.777778e+00
17,achados e perdidos,Achados e Perdidos,https://pt.wikipedia.org/wiki/Achados_e_Perdid...,Achados e perdidos,"Concha Celestino, Cris Gonzalez, Deborah Dorne...",2014.0,NaN,NaN,Fiction,pt-BR,e-galáxia,False,Achados e Perdidos,2007-04-19,2007.0,pt,Crime,92.0,NaN,NaN,1.2524,4.929,14.0,True,100.000000,100.000000,False,False,NaN
18,the adventures of tom sawyer,The Adventures of Tom Sawyer,https://pt.wikipedia.org/wiki/The_Adventures_o...,The Adventures of Tom Sawyer,Mark Twain,1999.0,4.0,6.0,Juvenile Fiction,en,Scholastic Inc.,True,As Aventuras de Tom Sawyer,1938-02-11,1938.0,en,"Família, Aventura",91.0,NaN,NaN,1.8598,6.600,53.0,True,100.000000,74.074074,False,False,NaN
19,o advogado do diabo,O Advogado do Diabo,https://pt.wikipedia.org/wiki/O_Advogado_do_Di...,O advogado do diabo,Morris West,1959.0,NaN,NaN,Não informado,pt-BR,Não informado,False,Advogado do Diabo,1997-10-17,1997.0,en,"Terror, Drama, Mistério",143.0,57000000.0,1.530000e+08,15.3540,7.482,7026.0,True,100.000000,94.444444,True,True,1.684211e+00
20,airport,Airport,https://pt.wikipedia.org/wiki/Airport,Local Climatological Data,Não informado,2007.0,NaN,NaN,Detroit (Mich.),en,Não informado,False,Aeroporto,1970-03-25,1970.0,en,"Drama, Thriller, Ação",137.0,10000000.0,1.004892e+08,3.7703,6.500,466.0,True,18.750000,75.000000,False,False,9.048915e+00
21,amanhecer,Amanhecer,https://pt.wikipedia.org/wiki/Amanhecer_(romance),Jaguars of the Dawn,Emily Pierini,2020.0,NaN,NaN,Religion,en,Berghahn Books,False,Antes do Amanhecer,1995-01-27,1995.0,en,"Drama, Romance",100.0,2500000.0,5.987386e+06,12.2711,7.969,4855.0,True,28.571429,66.666667,False,False,1.394954e+00
22,amar verbo intransitivo,"Amar, Verbo Intransitivo","https://pt.wikipedia.org/wiki/Amar,_Verbo_Intr...","Amar, verbo intransitivo (romance)",Mário de Andrade,1960.0,NaN,NaN,Brazilian literature,pt-BR,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,82.758621,NaN,False,False,NaN
23,psicopata americano,Psicopata Americano,https://pt.wikipedia.org/wiki/Psicopata_Americ...,O psicopata Americano,Bret Easton Ellis,1992.0,NaN,NaN,Não informado,pt-BR,Não informado,False,Psicopata Americano,2000-04-13,2000.0,en,"Thriller, Drama, Crime",102.0,7000000.0,3.426975e+07,17.8218,7.402,12700.0,True,95.000000,100.000000,True,True,3.895678e+00
24,de amor y de sombra,De amor y de sombra,https://pt.wikipedia.org/wiki/De_amor_y_de_sombra,De amor y de sombra,Isabel Allende,2009.0,NaN,NaN,Não informado,es,Não informado,False,De Amor e de Sombras,1994-05-10,1994.0,en,Drama,103.0,NaN,NaN,2.2914,5.405,105.0,True,100.000000,87.179487,False,False,NaN
25,lamour dure trois ans,L'amour dure trois ans,https://pt.wikipedia.org/wiki/L%27amour_dure_t...,Love Lasts Three Years,Kerry M. Harwin,2005.0,NaN,NaN,City and town life in literature,en,Não informado,False,L'amour dure trois ans,2011-12-10,2011.0,fr,"Romance, Comédia",98.0,NaN,NaN,1.7052,5.730,435.0,True,40.909091,100.000000,True,True,NaN
26,ana e o rei,Ana e o Rei,https://pt.wikipedia.org/wiki/Ana_e_o_Rei,Ana a manda,Ruy Duarte de Carvalho,1989.0,NaN,NaN,Angola,pt-BR,Não informado,False,Anna and the King,2000-01-01,2000.0,en,"Animação, Família",50.0,NaN,NaN,0.7847,7.000,3.0,True,36.363636,42.857143,True,False,NaN
27,ana terra,Ana Terra,https://pt.wikipedia.org/wiki/Ana_Terra,"Ana Theodora, mulher-do-chifre-furado",Mariana de Oliveira,1992.0,NaN,NaN,Women,pt-BR,Não informado,False,Ana Terra,1971-05-23,1971.0,pt,"Drama, História, Guerra",100.0,NaN,NaN,1.6791,9.500,2.0,True,34.782609,100.000000,False,False,NaN
28,antes que anochezca,Antes que anochezca,https://pt.wikipedia.org/wiki/Antes_que_anochezca,Antes Que Anochezca,Não informado,2001.0,NaN,NaN,Cuba,en,New Line Cinema Corporation,False,Prima che la notte,2018-05-23,2018.0,it,"Drama, Crime",118.0,NaN,NaN,0.7641,7.000,25.0,True,100.000000,48.648649,True,False,NaN
29,antes o mundo nao existia,Antes o Mundo Não Existia,https://pt.wikipedia.org/wiki/Antes_o_Mundo_N%...,Antes o mundo não existia,"Umúsin Panlõn Kumu, Tolamãn Kenhíri",1995.0,NaN,NaN,Desana mythology,pt-BR,Não informado,False,Rebojo: Antes o Mundo Não Existia,NaT,NaN,pt,"Fantasia, Mistério",5.0,1200.0,NaN,1.0247,0.000,0.0,True,100.000000,86.206897,False,False,NaN
30,appointment with death,Appointment with Death,https://pt.wikipedia.org/wiki/Appointment_with...,Appointment with Death,Agatha Christie,2011.0,NaN,NaN,Fiction,en,Harper Collins,False,Encontro Marcado com a Morte,1988-04-15,1988.0,en,"Thriller, Crime, Mistério, Drama",102.0,6000000.0,9.600400e+05,4.8204,6.098,193.0,True,100.000000,40.000000,False,False,-8.399933e-01
31,o aprendizado de pequena arvore,O Aprendizado de Pequena Árvore,https://pt.wikipedia.org/wiki/O_Aprendizado_de...,O aprendizado de Pequena Árvore,Forrest Carter,1994.0,NaN,NaN,Não informado,pt-BR,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
32,arthur et la cite interdite,Arthur et la Cité interdite,https://pt.wikipedia.org/wiki/Arthur_et_la_Cit...,Arthur et la cité interdite,"Luc Besson, Céline Garcia",2005.0,NaN,NaN,Não informado,fr,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
33,arthur et la guerre des deux mondes,Arthur et la Guerre des deux mondes,https://pt.wikipedia.org/wiki/Arthur_et_la_Gue...,Arthur 3 - La guerre des deux mondes,"Besson,",2010.0,NaN,NaN,Não informado,fr,Intervista,False,Arthur e a Guerra dos Dois Mundos,2010-08-22,2010.0,fr,"Animação, Aventura, Fantasia, Família",101.0,70200000.0,3.388598e+07,3.9550,5.815,1648.0,True,90.140845,73.529412,True,True,-5.172937e-01
34,arthur et la vengeance de maltazard,Arthur et la vengeance de Maltazard,https://pt.wikipedia.org/wiki/Arthur_et_la_ven...,Arthur et la vengeance de Maltazard,"Luc Besson, Stéphane Martinez, Robert Cepo",2009.0,NaN,NaN,Não informado,fr,Não informado,False,Arthur e a Vingança de Maltazard,2009-11-26,2009.0,fr,"Aventura, Fantasia, Animação, Família",93.0,87000000.0,5.237761e+07,4.9212,5.780,1816.0,True,100.000000,80.597015,True,True,-3.979585e-01
35,arthur et les minimoys,Arthur et les Minimoys,https://pt.wikipedia.org/wiki/Arthur_et_les_Mi...,Arthur et les minimoys T02,Jean-Christophe Derrien,2019.0,NaN,NaN,Comics & Graphic Novels,fr,Soleil,False,Arthur e os Minimoys,2006-12-13,2006.0,fr,"Aventura, Fantasia, Animação, Família",94.0,86000000.0,1.086056e+08,6.5825,6.394,3100.0,True,91.666667,80.952381,False,False,2.628559e-01
36,the killer inside me,The Killer Inside Me,https://pt.wikipedia.org/wiki/The_Killer_Insid...,The Killer Inside Me,Jim Thompson,2011.0,4.0,17.0,Fiction,en,Hachette+ORM,True,O Assassino em Mim,2010-02-19,2010.0,en,"Crime, Drama, Thriller",109.0,13000000.0,4.052191e+06,3.8908,5.831,650.0,True,100.000000,36.842105,True,False,-6.882930e-01
37,atlas shrugged,Atlas Shrugged,https://pt.wikipedia.org/wiki/Atlas_Shrugged,Atlas Shrugged,Ayn Rand,2005.0,4.0,6.0,Fiction,en,Penguin,True,A Revolta de Atlas Parte 1,2011-04-14,2011.0,en,"Drama, Thriller, Ficção científica, Mistério",102.0,20000000.0,4.627375e+06,3.9253,5.473,222.0,True,100.000000,40.000000,True,False,-7.686312e-01
38,atonement,Atonement,https://pt.wikipedia.org/wiki/Atonement_(livro),The Atonement,William Lane Craig,2018.0,NaN,NaN,Religion,en,Cambridge University Press,False,Desejo e Reparação,2007-02-27,2007.0,en,"Drama, Romance",123.0,30000000.0,1.310166e+08,11.9624,7.600,4828.0,True,81.818182,22.222222,False,False,3.367221e+00
39,austenlandia,Austenlândia,https://pt.wikipedia.org/wiki/Austenl%C3%A2ndia,Austenlândia,Shannon Hale,2014.0,NaN,NaN,Fiction,pt-BR,Editora Record,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
40,auto da compadecida,Auto da Compadecida,https://pt.wikipedia.org/wiki/Auto_da_Compadecida,Auto Da Compadecida,A. Suassuna,1967.0,NaN,NaN,Não informado,en,Não informado,False,O Auto da Compadecida,2000-09-15,2000.0,pt,"Comédia, Drama, Fantasia, Romance",104.0,NaN,4.903192e+06,5.6976,8.414,1244.0,True,100.000000,95.000000,True,True,NaN
41,autobiografia de uma pulga,Autobiografia de uma Pulga,https://pt.wikipedia.org/wiki/Autobiografia_de...,Autobiografia de uma pulga,Anônimo,2015.0,NaN,NaN,Fiction,pt-BR,hedra,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
42,as aventuras de huckleberry finn,As Aventuras de Huckleberry Finn,https://pt.wikipedia.org/wiki/As_Aventuras_de_...,As aventuras de Huckleberry Finn,Mark Twain,2011.0,NaN,NaN,Fiction,pt-BR,Editora Best Seller,False,As Aventuras de Huckleberry Finn,1974-05-24,1974.0,en,"Música, Família, Aventura",118.0,NaN,NaN,1.1936,5.969,16.0,True,100.000000,100.000000,False,False,NaN
43,basil of baker street,Basil of Baker Street,https://pt.wikipedia.org/wiki/Basil_of_Baker_S...,Basil of Baker Street,"Eve Titus, Paul Galdone",2016.0,NaN,NaN,Juvenile Fiction,en,Simon and Schuster,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
44,beleza e tristeza,Beleza e Tristeza,https://pt.wikipedia.org/wiki/Beleza_e_Tristeza,Beleza e tristeza,Yasunari Kawabata,2008.0,NaN,NaN,Não informado,pt-BR,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
45,benhur a tale of the christ,Ben-Hur: A Tale of the Christ,https://pt.wikipedia.org/wiki/Ben-Hur:_A_Tale_...,Ben-Hur: A tale of the Christ,Lew Wallace,2022.0,NaN,NaN,Fiction,en,DigiCat,False,Ben-Hur,1925-12-25,1925.0,en,"Aventura, Drama, Romance, Ação",143.0,3900000.0,9.000000e+06,2.3702,7.323,116.0,True,100.000000,38.888889,False,False,1.307692e+00
46,benjamim,Benjamim,https://pt.wikipedia.org/wiki/Benjamim_(romance),Circo-Teatro: Benjamim de Oliveira e a teatral...,Ermínia Silva,2022.0,NaN,NaN,Education,pt-BR,Digitaliza Conteudo,False,Benjamim,2003-10-21,2003.0,pt,"Romance, Drama",100.0,NaN,NaN,0.8715,5.150,10.0,True,20.512821,100.000000,False,False,NaN
47,between a rock and a hard place,Between a Rock and a Hard Place,https://pt.wikipedia.org/wiki/Between_a_Rock_a...,Between a Rock and a Hard Place,Aron Ralston,2004.0,3.5,13.0,Biography & Autobiography,en,Simon and Schuster,True,Mellem sten og et hårdt sted,2019-08-26,2019.0,da,Drama,19.0,NaN,NaN,1.1276,0.000,0.0,True,100.000000,37.288136,True,False,NaN
48,the bicentennial man and other stories,The Bicentennial Man and Other Stories,https://pt.wikipedia.org/wiki/The_Bicentennial...,The Bicentennial Man and Other Stories,Isaac Asimov,1981.0,5.0,1.0,Não informado,en,Fawcett,True,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
49,die biene maja,Die Biene Maja,https://pt.wikipedia.org/wiki/Die_Biene_Maja,Die Biene Maja Und Ihre Abenteuer,"Waldemar Bonsels, Franz Schneider, Martha Boyd",2026.0,NaN,NaN,Language Study,en,Tradd Street Press,False,Die Biene Maja und ihre Abenteuer,1926-04-08,1926.0,de,Não informado,76.0,NaN,NaN,1.0609,8.000,1.0,True,59.574468,59.574468,False,False,NaN
50,born free,Born Free,https://pt.wikipedia.org/wiki/Born_Free,Born Free,Robert Leslie Free,2007.0,NaN,NaN,Darling Downs (Qld.),en,Não informado,False,A História de Elza,1966-03-14,1966.0,en,"Aventura, Família, Drama, História",95.0,NaN,NaN,2.4559,6.800,133.0,True,100.000000,22.222222,False,False,NaN
51,the boy in the striped pyjamas,The Boy in the Striped Pyjamas,https://pt.wikipedia.org/wiki/The_Boy_in_the_S...,The Boy in the Striped Pajamas (Deluxe Illustr...,John Boyne,2017.0,5.0,2.0,Young Adult Fiction,en,Knopf Books for Young Readers,True,O Menino do Pijama Listrado,2008-05-07,2008.0,en,"Drama, Guerra, História",94.0,12500000.0,2.041656e+07,18.3760,7.800,7823.0,True,65.168539,35.087719,False,False,6.333250e-01
52,breve romance de sonho,Breve Romance de Sonho,https://pt.wikipedia.org/wiki/Breve_Romance_de...,Breve romance de sonho,Arthur Schnitzler,2008.0,NaN,NaN,Fiction,pt-BR,Editora Companhia das Letras,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN
53,budapeste,Budapeste,https://pt.wikipedia.org/wiki/Budapeste_(livro),Budapeste,Chico Buarque,2009.0,NaN,NaN,Não informado,pt-BR,Não informado,False,O Grande Hotel Budapeste,2014-02-26,2014.0,en,"Comédia, Drama",100.0,30000000.0,1.746003e+08,17.9979,8.025,16481.0,True,100.000000,54.545455,True,False,4.820011e+00
54,buddenbrooks verfall einer familie,Buddenbrooks: Verfall einer Familie,https://pt.wikipedia.org/wiki/Buddenbrooks:_Ve...,Buddenbrooks,Thomas Mann,1916.0,NaN,NaN,Não informado,en,Não informado,False,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,51.063830,NaN,False,False,NaN
55,bufo spallanzani,Bufo & Spallanzani,https://pt.wikipedia.org/wiki/Bufo_%26_Spallan...,Bufo & Spallanzani,Rubem Fonseca,1990.0,3.5,2.0,Fiction,en,Não informado,True,Bufo & Spallanzani,2001-08-31,2001.0,pt,"Crime, Mistério",101.0,NaN,NaN,2.1926,5.000,11.0,True,100.000000,100.000000,True,True,NaN
56,o cabeleira,O Cabeleira,https://pt.wikipedia.org/wiki/O_Cabeleira,O Cabeleira,Franklin Távora,2018.0,NaN,NaN,Não informado,pt-BR,Não informado,False,O Cabeleira,1963-01-01,1963.0,pt,"Aventura, Drama",86.0,NaN,NaN,4.7144,7.000,1.0,True,100.000000,100.000000,False,False,NaN
57,call for the dead,Call for the Dead,https://pt.wikipedia.org/wiki/Call_for_the_Dead,Call for the Dead,John le Carre,2002.0,4.0,5.0,Fiction,en,Simon and Schuster,True,None,NaT,NaN,Não informado,Não informado,NaN,NaN,NaN,NaN,NaN,NaN,False,100.000000,NaN,False,False,NaN

In [ ]:
!zip -r dados_brutos.zip dados_brutos
!zip -r dados_tratados.zip dados_tratados

updating: dados_brutos/ (stored 0%)
updating: dados_brutos/tmdb_resultados.csv (deflated 59%)
updating: dados_brutos/tmdb_json/ (stored 0%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0266.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0287.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0390.json (deflated 30%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0092.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_busca_0359.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0024.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0225.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0347.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_busca_0183.json (deflated 55%)
updating: dados_brutos/tmdb_json/tmdb_busca_0418.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0104.json (deflated 66%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0135.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0365.json (deflated 49%)
updating: dados_brutos/tmdb_json/tmdb_busca_0330.json (deflated 65%)
updating: dados_brutos/tmdb_json/tmdb_busca_0290.json (deflated 32%)
updating: dados_brutos/tmdb_json/tmdb_busca_0423.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_busca_0406.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0372.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0143.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0055.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0062.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0262.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0086.json (deflated 60%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0175.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0107.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0260.json (deflated 60%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0221.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0341.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0037.json (deflated 53%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0085.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0164.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0238.json (deflated 50%)
updating: dados_brutos/tmdb_json/tmdb_busca_0153.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0129.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0365.json (deflated 67%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0395.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0026.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0246.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0385.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0370.json (deflated 67%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0052.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0285.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0385.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0141.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0294.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_busca_0028.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0217.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0393.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0259.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0140.json (deflated 35%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0286.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0305.json (deflated 37%)
updating: dados_brutos/tmdb_json/tmdb_busca_0216.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0106.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_busca_0036.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0417.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0162.json (deflated 37%)
updating: dados_brutos/tmdb_json/tmdb_busca_0343.json (deflated 65%)
updating: dados_brutos/tmdb_json/tmdb_busca_0064.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_busca_0178.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0352.json (deflated 64%)
updating: dados_brutos/tmdb_json/tmdb_busca_0083.json (deflated 64%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0080.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0363.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0403.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0166.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0274.json (deflated 56%)
updating: dados_brutos/tmdb_json/tmdb_busca_0379.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_busca_0378.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_busca_0329.json (deflated 72%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0256.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0334.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0185.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0243.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0146.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0297.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0292.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0167.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0281.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0163.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0390.json (deflated 48%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0282.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0030.json (deflated 35%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0412.json (deflated 36%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0238.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0277.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0132.json (deflated 64%)
updating: dados_brutos/tmdb_json/tmdb_busca_0409.json (deflated 64%)
updating: dados_brutos/tmdb_json/tmdb_busca_0074.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0319.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0352.json (deflated 54%)
updating: dados_brutos/tmdb_json/tmdb_busca_0302.json (deflated 74%)
updating: dados_brutos/tmdb_json/tmdb_busca_0174.json (deflated 49%)
updating: dados_brutos/tmdb_json/tmdb_busca_0207.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0153.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0044.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0177.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0306.json (deflated 49%)
updating: dados_brutos/tmdb_json/tmdb_busca_0272.json (deflated 35%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0090.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0196.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0190.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0224.json (deflated 36%)
updating: dados_brutos/tmdb_json/tmdb_busca_0181.json (deflated 65%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0320.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0161.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0344.json (deflated 69%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0344.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0117.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0223.json (deflated 36%)
updating: dados_brutos/tmdb_json/tmdb_busca_0323.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0229.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0263.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0134.json (deflated 55%)
updating: dados_brutos/tmdb_json/tmdb_busca_0144.json (deflated 53%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0219.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0105.json (deflated 51%)
updating: dados_brutos/tmdb_json/tmdb_busca_0257.json (deflated 51%)
updating: dados_brutos/tmdb_json/tmdb_busca_0060.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_busca_0395.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0421.json (deflated 65%)
updating: dados_brutos/tmdb_json/tmdb_busca_0008.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0029.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0045.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0101.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0404.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0221.json (deflated 69%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0354.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0353.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_busca_0206.json (deflated 55%)
updating: dados_brutos/tmdb_json/tmdb_busca_0340.json (deflated 68%)
updating: dados_brutos/tmdb_json/tmdb_busca_0203.json (deflated 73%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0232.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0313.json (deflated 56%)
updating: dados_brutos/tmdb_json/tmdb_busca_0166.json (deflated 36%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0205.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_busca_0130.json (deflated 37%)
updating: dados_brutos/tmdb_json/tmdb_busca_0227.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0324.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0208.json (deflated 35%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0307.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0318.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0255.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0245.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_busca_0243.json (deflated 48%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0202.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0097.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0298.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0361.json (deflated 48%)
updating: dados_brutos/tmdb_json/tmdb_busca_0377.json (deflated 66%)
updating: dados_brutos/tmdb_json/tmdb_busca_0042.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0206.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0236.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0295.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0292.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0301.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0267.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0108.json (deflated 51%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0273.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0414.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0152.json (deflated 56%)
updating: dados_brutos/tmdb_json/tmdb_busca_0397.json (deflated 62%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0066.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0072.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0091.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0322.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0098.json (deflated 73%)
updating: dados_brutos/tmdb_json/tmdb_busca_0126.json (deflated 55%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0178.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0298.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0369.json (deflated 58%)
updating: dados_brutos/tmdb_json/tmdb_busca_0039.json (deflated 73%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0186.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0374.json (deflated 66%)
updating: dados_brutos/tmdb_json/tmdb_busca_0247.json (deflated 51%)
updating: dados_brutos/tmdb_json/tmdb_busca_0150.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0301.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0147.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0135.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_busca_0053.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0250.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0410.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0010.json (deflated 35%)
updating: dados_brutos/tmdb_json/tmdb_busca_0007.json (deflated 32%)
updating: dados_brutos/tmdb_json/tmdb_busca_0381.json (deflated 62%)
updating: dados_brutos/tmdb_json/tmdb_busca_0252.json (deflated 61%)
updating: dados_brutos/tmdb_json/tmdb_busca_0107.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0100.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0272.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0155.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0327.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0419.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0180.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0096.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0046.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0368.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0152.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0088.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_busca_0228.json (deflated 30%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0025.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0348.json (deflated 31%)
updating: dados_brutos/tmdb_json/tmdb_busca_0149.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_busca_0032.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0376.json (deflated 31%)
updating: dados_brutos/tmdb_json/tmdb_busca_0155.json (deflated 65%)
updating: dados_brutos/tmdb_json/tmdb_busca_0034.json (deflated 36%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0214.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_busca_0079.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0339.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0161.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0224.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0181.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0244.json (deflated 58%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0028.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0048.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0041.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0019.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0222.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0147.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0377.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0169.json (deflated 30%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0294.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0131.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0380.json (deflated 74%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0413.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_busca_0350.json (deflated 64%)
updating: dados_brutos/tmdb_json/tmdb_busca_0400.json (deflated 34%)
updating: dados_brutos/tmdb_json/tmdb_busca_0328.json (deflated 37%)
updating: dados_brutos/tmdb_json/tmdb_busca_0268.json (deflated 72%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0326.json (deflated 50%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0191.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0411.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0389.json (deflated 47%)
updating: dados_brutos/tmdb_json/tmdb_busca_0407.json (deflated 69%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0133.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0297.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0057.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0031.json (deflated 57%)
updating: dados_brutos/tmdb_json/tmdb_busca_0091.json (deflated 52%)
updating: dados_brutos/tmdb_json/tmdb_busca_0255.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0021.json (deflated 44%)
updating: dados_brutos/tmdb_json/tmdb_busca_0358.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0038.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0195.json (deflated 63%)
updating: dados_brutos/tmdb_json/tmdb_busca_0094.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0198.json (deflated 48%)
updating: dados_brutos/tmdb_json/tmdb_busca_0072.json (deflated 60%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0347.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0115.json (deflated 60%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0373.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0321.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0080.json (deflated 79%)
updating: dados_brutos/tmdb_json/tmdb_busca_0117.json (deflated 49%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0252.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0362.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_busca_0095.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0125.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0088.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_busca_0335.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_busca_0128.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_busca_0059.json (deflated 32%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0241.json (deflated 40%)
updating: dados_brutos/tmdb_json/tmdb_busca_0076.json (deflated 73%)
updating: dados_brutos/tmdb_json/tmdb_busca_0049.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0290.json (deflated 38%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0073.json (deflated 45%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0004.json (deflated 39%)
updating: dados_brutos/tmdb_json/tmdb_busca_0324.json (deflated 55%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0173.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_busca_0271.json (deflated 60%)
updating: dados_brutos/tmdb_json/tmdb_busca_0231.json (deflated 74%)
updating: dados_brutos/tmdb_json/tmdb_busca_0200.json (deflated 59%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0313.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0180.json (deflated 33%)
updating: dados_brutos/tmdb_json/tmdb_busca_0279.json (deflated 31%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0119.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_busca_0276.json (deflated 26%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0061.json (deflated 46%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0069.json (deflated 42%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0249.json (deflated 43%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0046.json (deflated 41%)
updating: dados_brutos/tmdb_json/tmdb_detalhes_0024.json (deflated 45%)